// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package tokenfactory

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_LiquidityUnlocking                      protoreflect.MessageDescriptor
	fd_LiquidityUnlocking_index                protoreflect.FieldDescriptor
	fd_LiquidityUnlocking_factory_denom_hash   protoreflect.FieldDescriptor
	fd_LiquidityUnlocking_k_coin               protoreflect.FieldDescriptor
	fd_LiquidityUnlocking_address              protoreflect.FieldDescriptor
	fd_LiquidityUnlocking_created_at           protoreflect.FieldDescriptor
	fd_LiquidityUnlocking_factory_denom_amount protoreflect.FieldDescriptor
	fd_LiquidityUnlocking_k_coin_amount        protoreflect.FieldDescriptor
)

func init() {
	file_kopi_tokenfactory_unlocking_proto_init()
	md_LiquidityUnlocking = File_kopi_tokenfactory_unlocking_proto.Messages().ByName("LiquidityUnlocking")
	fd_LiquidityUnlocking_index = md_LiquidityUnlocking.Fields().ByName("index")
	fd_LiquidityUnlocking_factory_denom_hash = md_LiquidityUnlocking.Fields().ByName("factory_denom_hash")
	fd_LiquidityUnlocking_k_coin = md_LiquidityUnlocking.Fields().ByName("k_coin")
	fd_LiquidityUnlocking_address = md_LiquidityUnlocking.Fields().ByName("address")
	fd_LiquidityUnlocking_created_at = md_LiquidityUnlocking.Fields().ByName("created_at")
	fd_LiquidityUnlocking_factory_denom_amount = md_LiquidityUnlocking.Fields().ByName("factory_denom_amount")
	fd_LiquidityUnlocking_k_coin_amount = md_LiquidityUnlocking.Fields().ByName("k_coin_amount")
}

var _ protoreflect.Message = (*fastReflection_LiquidityUnlocking)(nil)

type fastReflection_LiquidityUnlocking LiquidityUnlocking

func (x *LiquidityUnlocking) ProtoReflect() protoreflect.Message {
	return (*fastReflection_LiquidityUnlocking)(x)
}

func (x *LiquidityUnlocking) slowProtoReflect() protoreflect.Message {
	mi := &file_kopi_tokenfactory_unlocking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_LiquidityUnlocking_messageType fastReflection_LiquidityUnlocking_messageType
var _ protoreflect.MessageType = fastReflection_LiquidityUnlocking_messageType{}

type fastReflection_LiquidityUnlocking_messageType struct{}

func (x fastReflection_LiquidityUnlocking_messageType) Zero() protoreflect.Message {
	return (*fastReflection_LiquidityUnlocking)(nil)
}
func (x fastReflection_LiquidityUnlocking_messageType) New() protoreflect.Message {
	return new(fastReflection_LiquidityUnlocking)
}
func (x fastReflection_LiquidityUnlocking_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_LiquidityUnlocking
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_LiquidityUnlocking) Descriptor() protoreflect.MessageDescriptor {
	return md_LiquidityUnlocking
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_LiquidityUnlocking) Type() protoreflect.MessageType {
	return _fastReflection_LiquidityUnlocking_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_LiquidityUnlocking) New() protoreflect.Message {
	return new(fastReflection_LiquidityUnlocking)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_LiquidityUnlocking) Interface() protoreflect.ProtoMessage {
	return (*LiquidityUnlocking)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_LiquidityUnlocking) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Index != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Index)
		if !f(fd_LiquidityUnlocking_index, value) {
			return
		}
	}
	if x.FactoryDenomHash != "" {
		value := protoreflect.ValueOfString(x.FactoryDenomHash)
		if !f(fd_LiquidityUnlocking_factory_denom_hash, value) {
			return
		}
	}
	if x.KCoin != "" {
		value := protoreflect.ValueOfString(x.KCoin)
		if !f(fd_LiquidityUnlocking_k_coin, value) {
			return
		}
	}
	if x.Address != "" {
		value := protoreflect.ValueOfString(x.Address)
		if !f(fd_LiquidityUnlocking_address, value) {
			return
		}
	}
	if x.CreatedAt != nil {
		value := protoreflect.ValueOfMessage(x.CreatedAt.ProtoReflect())
		if !f(fd_LiquidityUnlocking_created_at, value) {
			return
		}
	}
	if len(x.FactoryDenomAmount) != 0 {
		value := protoreflect.ValueOfBytes(x.FactoryDenomAmount)
		if !f(fd_LiquidityUnlocking_factory_denom_amount, value) {
			return
		}
	}
	if len(x.KCoinAmount) != 0 {
		value := protoreflect.ValueOfBytes(x.KCoinAmount)
		if !f(fd_LiquidityUnlocking_k_coin_amount, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_LiquidityUnlocking) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "kopi.tokenfactory.LiquidityUnlocking.index":
		return x.Index != uint64(0)
	case "kopi.tokenfactory.LiquidityUnlocking.factory_denom_hash":
		return x.FactoryDenomHash != ""
	case "kopi.tokenfactory.LiquidityUnlocking.k_coin":
		return x.KCoin != ""
	case "kopi.tokenfactory.LiquidityUnlocking.address":
		return x.Address != ""
	case "kopi.tokenfactory.LiquidityUnlocking.created_at":
		return x.CreatedAt != nil
	case "kopi.tokenfactory.LiquidityUnlocking.factory_denom_amount":
		return len(x.FactoryDenomAmount) != 0
	case "kopi.tokenfactory.LiquidityUnlocking.k_coin_amount":
		return len(x.KCoinAmount) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: kopi.tokenfactory.LiquidityUnlocking"))
		}
		panic(fmt.Errorf("message kopi.tokenfactory.LiquidityUnlocking does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LiquidityUnlocking) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "kopi.tokenfactory.LiquidityUnlocking.index":
		x.Index = uint64(0)
	case "kopi.tokenfactory.LiquidityUnlocking.factory_denom_hash":
		x.FactoryDenomHash = ""
	case "kopi.tokenfactory.LiquidityUnlocking.k_coin":
		x.KCoin = ""
	case "kopi.tokenfactory.LiquidityUnlocking.address":
		x.Address = ""
	case "kopi.tokenfactory.LiquidityUnlocking.created_at":
		x.CreatedAt = nil
	case "kopi.tokenfactory.LiquidityUnlocking.factory_denom_amount":
		x.FactoryDenomAmount = nil
	case "kopi.tokenfactory.LiquidityUnlocking.k_coin_amount":
		x.KCoinAmount = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: kopi.tokenfactory.LiquidityUnlocking"))
		}
		panic(fmt.Errorf("message kopi.tokenfactory.LiquidityUnlocking does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_LiquidityUnlocking) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "kopi.tokenfactory.LiquidityUnlocking.index":
		value := x.Index
		return protoreflect.ValueOfUint64(value)
	case "kopi.tokenfactory.LiquidityUnlocking.factory_denom_hash":
		value := x.FactoryDenomHash
		return protoreflect.ValueOfString(value)
	case "kopi.tokenfactory.LiquidityUnlocking.k_coin":
		value := x.KCoin
		return protoreflect.ValueOfString(value)
	case "kopi.tokenfactory.LiquidityUnlocking.address":
		value := x.Address
		return protoreflect.ValueOfString(value)
	case "kopi.tokenfactory.LiquidityUnlocking.created_at":
		value := x.CreatedAt
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "kopi.tokenfactory.LiquidityUnlocking.factory_denom_amount":
		value := x.FactoryDenomAmount
		return protoreflect.ValueOfBytes(value)
	case "kopi.tokenfactory.LiquidityUnlocking.k_coin_amount":
		value := x.KCoinAmount
		return protoreflect.ValueOfBytes(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: kopi.tokenfactory.LiquidityUnlocking"))
		}
		panic(fmt.Errorf("message kopi.tokenfactory.LiquidityUnlocking does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LiquidityUnlocking) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "kopi.tokenfactory.LiquidityUnlocking.index":
		x.Index = value.Uint()
	case "kopi.tokenfactory.LiquidityUnlocking.factory_denom_hash":
		x.FactoryDenomHash = value.Interface().(string)
	case "kopi.tokenfactory.LiquidityUnlocking.k_coin":
		x.KCoin = value.Interface().(string)
	case "kopi.tokenfactory.LiquidityUnlocking.address":
		x.Address = value.Interface().(string)
	case "kopi.tokenfactory.LiquidityUnlocking.created_at":
		x.CreatedAt = value.Message().Interface().(*timestamppb.Timestamp)
	case "kopi.tokenfactory.LiquidityUnlocking.factory_denom_amount":
		x.FactoryDenomAmount = value.Bytes()
	case "kopi.tokenfactory.LiquidityUnlocking.k_coin_amount":
		x.KCoinAmount = value.Bytes()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: kopi.tokenfactory.LiquidityUnlocking"))
		}
		panic(fmt.Errorf("message kopi.tokenfactory.LiquidityUnlocking does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LiquidityUnlocking) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "kopi.tokenfactory.LiquidityUnlocking.created_at":
		if x.CreatedAt == nil {
			x.CreatedAt = new(timestamppb.Timestamp)
		}
		return protoreflect.ValueOfMessage(x.CreatedAt.ProtoReflect())
	case "kopi.tokenfactory.LiquidityUnlocking.index":
		panic(fmt.Errorf("field index of message kopi.tokenfactory.LiquidityUnlocking is not mutable"))
	case "kopi.tokenfactory.LiquidityUnlocking.factory_denom_hash":
		panic(fmt.Errorf("field factory_denom_hash of message kopi.tokenfactory.LiquidityUnlocking is not mutable"))
	case "kopi.tokenfactory.LiquidityUnlocking.k_coin":
		panic(fmt.Errorf("field k_coin of message kopi.tokenfactory.LiquidityUnlocking is not mutable"))
	case "kopi.tokenfactory.LiquidityUnlocking.address":
		panic(fmt.Errorf("field address of message kopi.tokenfactory.LiquidityUnlocking is not mutable"))
	case "kopi.tokenfactory.LiquidityUnlocking.factory_denom_amount":
		panic(fmt.Errorf("field factory_denom_amount of message kopi.tokenfactory.LiquidityUnlocking is not mutable"))
	case "kopi.tokenfactory.LiquidityUnlocking.k_coin_amount":
		panic(fmt.Errorf("field k_coin_amount of message kopi.tokenfactory.LiquidityUnlocking is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: kopi.tokenfactory.LiquidityUnlocking"))
		}
		panic(fmt.Errorf("message kopi.tokenfactory.LiquidityUnlocking does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_LiquidityUnlocking) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "kopi.tokenfactory.LiquidityUnlocking.index":
		return protoreflect.ValueOfUint64(uint64(0))
	case "kopi.tokenfactory.LiquidityUnlocking.factory_denom_hash":
		return protoreflect.ValueOfString("")
	case "kopi.tokenfactory.LiquidityUnlocking.k_coin":
		return protoreflect.ValueOfString("")
	case "kopi.tokenfactory.LiquidityUnlocking.address":
		return protoreflect.ValueOfString("")
	case "kopi.tokenfactory.LiquidityUnlocking.created_at":
		m := new(timestamppb.Timestamp)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "kopi.tokenfactory.LiquidityUnlocking.factory_denom_amount":
		return protoreflect.ValueOfBytes(nil)
	case "kopi.tokenfactory.LiquidityUnlocking.k_coin_amount":
		return protoreflect.ValueOfBytes(nil)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: kopi.tokenfactory.LiquidityUnlocking"))
		}
		panic(fmt.Errorf("message kopi.tokenfactory.LiquidityUnlocking does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_LiquidityUnlocking) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in kopi.tokenfactory.LiquidityUnlocking", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_LiquidityUnlocking) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LiquidityUnlocking) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_LiquidityUnlocking) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_LiquidityUnlocking) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*LiquidityUnlocking)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Index != 0 {
			n += 1 + runtime.Sov(uint64(x.Index))
		}
		l = len(x.FactoryDenomHash)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.KCoin)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Address)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.CreatedAt != nil {
			l = options.Size(x.CreatedAt)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.FactoryDenomAmount)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.KCoinAmount)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*LiquidityUnlocking)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.KCoinAmount) > 0 {
			i -= len(x.KCoinAmount)
			copy(dAtA[i:], x.KCoinAmount)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.KCoinAmount)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.FactoryDenomAmount) > 0 {
			i -= len(x.FactoryDenomAmount)
			copy(dAtA[i:], x.FactoryDenomAmount)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.FactoryDenomAmount)))
			i--
			dAtA[i] = 0x32
		}
		if x.CreatedAt != nil {
			encoded, err := options.Marshal(x.CreatedAt)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.Address) > 0 {
			i -= len(x.Address)
			copy(dAtA[i:], x.Address)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Address)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.KCoin) > 0 {
			i -= len(x.KCoin)
			copy(dAtA[i:], x.KCoin)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.KCoin)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.FactoryDenomHash) > 0 {
			i -= len(x.FactoryDenomHash)
			copy(dAtA[i:], x.FactoryDenomHash)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.FactoryDenomHash)))
			i--
			dAtA[i] = 0x12
		}
		if x.Index != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Index))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*LiquidityUnlocking)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: LiquidityUnlocking: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: LiquidityUnlocking: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				x.Index = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Index |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field FactoryDenomHash", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.FactoryDenomHash = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field KCoin", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.KCoin = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Address = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.CreatedAt == nil {
					x.CreatedAt = &timestamppb.Timestamp{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.CreatedAt); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field FactoryDenomAmount", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.FactoryDenomAmount = append(x.FactoryDenomAmount[:0], dAtA[iNdEx:postIndex]...)
				if x.FactoryDenomAmount == nil {
					x.FactoryDenomAmount = []byte{}
				}
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field KCoinAmount", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.KCoinAmount = append(x.KCoinAmount[:0], dAtA[iNdEx:postIndex]...)
				if x.KCoinAmount == nil {
					x.KCoinAmount = []byte{}
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: kopi/tokenfactory/unlocking.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LiquidityUnlocking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index              uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	FactoryDenomHash   string                 `protobuf:"bytes,2,opt,name=factory_denom_hash,json=factoryDenomHash,proto3" json:"factory_denom_hash,omitempty"`
	KCoin              string                 `protobuf:"bytes,3,opt,name=k_coin,json=kCoin,proto3" json:"k_coin,omitempty"`
	Address            string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FactoryDenomAmount []byte                 `protobuf:"bytes,6,opt,name=factory_denom_amount,json=factoryDenomAmount,proto3" json:"factory_denom_amount,omitempty"`
	KCoinAmount        []byte                 `protobuf:"bytes,7,opt,name=k_coin_amount,json=kCoinAmount,proto3" json:"k_coin_amount,omitempty"`
}

func (x *LiquidityUnlocking) Reset() {
	*x = LiquidityUnlocking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kopi_tokenfactory_unlocking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiquidityUnlocking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiquidityUnlocking) ProtoMessage() {}

// Deprecated: Use LiquidityUnlocking.ProtoReflect.Descriptor instead.
func (*LiquidityUnlocking) Descriptor() ([]byte, []int) {
	return file_kopi_tokenfactory_unlocking_proto_rawDescGZIP(), []int{0}
}

func (x *LiquidityUnlocking) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LiquidityUnlocking) GetFactoryDenomHash() string {
	if x != nil {
		return x.FactoryDenomHash
	}
	return ""
}

func (x *LiquidityUnlocking) GetKCoin() string {
	if x != nil {
		return x.KCoin
	}
	return ""
}

func (x *LiquidityUnlocking) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *LiquidityUnlocking) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LiquidityUnlocking) GetFactoryDenomAmount() []byte {
	if x != nil {
		return x.FactoryDenomAmount
	}
	return nil
}

func (x *LiquidityUnlocking) GetKCoinAmount() []byte {
	if x != nil {
		return x.KCoinAmount
	}
	return nil
}

var File_kopi_tokenfactory_unlocking_proto protoreflect.FileDescriptor

var file_kopi_tokenfactory_unlocking_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6b, 0x6f, 0x70, 0x69, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x66, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x79, 0x2f, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x6b, 0x6f, 0x70, 0x69, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x66,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf7, 0x02,
	0x0a, 0x12, 0x4c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x55, 0x6e, 0x6c, 0x6f, 0x63,
	0x6b, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2c, 0x0a, 0x12, 0x66, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x5f, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x44,
	0x65, 0x6e, 0x6f, 0x6d, 0x48, 0x61, 0x73, 0x68, 0x12, 0x15, 0x0a, 0x06, 0x6b, 0x5f, 0x63, 0x6f,
	0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6b, 0x43, 0x6f, 0x69, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x58, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x1d, 0xc8, 0xde, 0x1f, 0x01, 0xf2,
	0xde, 0x1f, 0x11, 0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x22, 0x90, 0xdf, 0x1f, 0x01, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x4f, 0x0a, 0x14, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x64,
	0x65, 0x6e, 0x6f, 0x6d, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0c, 0x42, 0x1d, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde, 0x1f, 0x15, 0x63, 0x6f, 0x73, 0x6d, 0x6f,
	0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x49, 0x6e, 0x74,
	0x52, 0x12, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x44, 0x65, 0x6e, 0x6f, 0x6d, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x41, 0x0a, 0x0d, 0x6b, 0x5f, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x1d, 0xc8, 0xde, 0x1f,
	0x00, 0xda, 0xde, 0x1f, 0x15, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69,
	0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x49, 0x6e, 0x74, 0x52, 0x0b, 0x6b, 0x43, 0x6f, 0x69,
	0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0xb0, 0x01, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x2e,
	0x6b, 0x6f, 0x70, 0x69, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x42, 0x0e, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x22, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69,
	0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6b, 0x6f, 0x70, 0x69, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0xa2, 0x02, 0x03, 0x4b, 0x54, 0x58, 0xaa, 0x02, 0x11,
	0x4b, 0x6f, 0x70, 0x69, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0xca, 0x02, 0x11, 0x4b, 0x6f, 0x70, 0x69, 0x5c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x66, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0xe2, 0x02, 0x1d, 0x4b, 0x6f, 0x70, 0x69, 0x5c, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x12, 0x4b, 0x6f, 0x70, 0x69, 0x3a, 0x3a, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_kopi_tokenfactory_unlocking_proto_rawDescOnce sync.Once
	file_kopi_tokenfactory_unlocking_proto_rawDescData = file_kopi_tokenfactory_unlocking_proto_rawDesc
)

func file_kopi_tokenfactory_unlocking_proto_rawDescGZIP() []byte {
	file_kopi_tokenfactory_unlocking_proto_rawDescOnce.Do(func() {
		file_kopi_tokenfactory_unlocking_proto_rawDescData = protoimpl.X.CompressGZIP(file_kopi_tokenfactory_unlocking_proto_rawDescData)
	})
	return file_kopi_tokenfactory_unlocking_proto_rawDescData
}

var file_kopi_tokenfactory_unlocking_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kopi_tokenfactory_unlocking_proto_goTypes = []interface{}{
	(*LiquidityUnlocking)(nil),    // 0: kopi.tokenfactory.LiquidityUnlocking
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_kopi_tokenfactory_unlocking_proto_depIdxs = []int32{
	1, // 0: kopi.tokenfactory.LiquidityUnlocking.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kopi_tokenfactory_unlocking_proto_init() }
func file_kopi_tokenfactory_unlocking_proto_init() {
	if File_kopi_tokenfactory_unlocking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kopi_tokenfactory_unlocking_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiquidityUnlocking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kopi_tokenfactory_unlocking_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kopi_tokenfactory_unlocking_proto_goTypes,
		DependencyIndexes: file_kopi_tokenfactory_unlocking_proto_depIdxs,
		MessageInfos:      file_kopi_tokenfactory_unlocking_proto_msgTypes,
	}.Build()
	File_kopi_tokenfactory_unlocking_proto = out.File
	file_kopi_tokenfactory_unlocking_proto_rawDesc = nil
	file_kopi_tokenfactory_unlocking_proto_goTypes = nil
	file_kopi_tokenfactory_unlocking_proto_depIdxs = nil
}
