syntax = "proto3";
package kopi.tokenfactory;

import "google/protobuf/timestamp.proto";
import "gogoproto/gogo.proto";

option go_package = "github.com/kopi-money/kopi/x/tokenfactory/types";

message TokenConversionEntry {
  string new_token = 1;

  bytes conversion_rate = 2 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable) = false
  ];
}

message TokenConversion {
  repeated TokenConversionEntry entries = 1 [
    (gogoproto.nullable) = false
  ];
}

message GenesisTokenConversion {
  string factory_denom_full_name = 1;
  repeated TokenConversionEntry entries = 2 [
    (gogoproto.nullable) = false
  ];
}

message TokenConversionCreation {
  string denom = 1;
  string conversation_rate = 2;
}
