syntax = "proto3";
package kopi.tokenfactory;

import "amino/amino.proto";
import "gogoproto/gogo.proto";

option go_package = "github.com/kopi-money/kopi/x/tokenfactory/types";

// Params defines the parameters for the module.
message Params {
  option (amino.name) = "kopi/x/tokenfactory/Params";
  option (gogoproto.equal) = true;

  int64 minimum_unlock_in_seconds = 1;

  bytes creation_fee = 2 [
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable)   = false
  ];

  bytes reserve_fee = 3 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable)   = false
  ];

  bytes minimum_pool_size = 4 [
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable)   = false
  ];
}
