syntax = "proto3";
package kopi.tokenfactory;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "cosmos/base/query/v1beta1/pagination.proto";
import "kopi/tokenfactory/params.proto";
import "kopi/tokenfactory/denoms.proto";

option go_package = "github.com/kopi-money/kopi/x/tokenfactory/types";

// Query defines the gRPC querier service.
service Query {
  // Parameters queries the parameters of the module.
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/params";
  }

  rpc Denoms (QueryDenomsRequest) returns (QueryDenomsResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/denoms";
  }

  rpc GetPool (QueryPoolRequest) returns (QueryPoolResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/denoms/pool";
  }

  rpc GetFactoryTokenBalance (GetFactoryTokenBalanceRequest) returns (GetFactoryTokenBalanceResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/balance/{address}";
  }

  rpc GetPoolLiquidityAddress (QueryPoolLiquidityAddressRequest) returns (QueryPoolLiquidityAddressResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/denoms/pool/{address}";
  }

  rpc QuerySimulateAddingLiquidityKCoin (QuerySimulateAddingLiquidityRequest) returns (QuerySimulateAddingLiquidityResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/denoms/pool/add/kcoin";
  }

  rpc QuerySimulateAddingLiquidityFactoryToken (QuerySimulateAddingLiquidityRequest) returns (QuerySimulateAddingLiquidityResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/denoms/pool/add/factory";
  }

  rpc QuerySimulateSell (QuerySimulateTradeRequest) returns (QuerySimulateTradeResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/simulate/sell";
  }

  rpc QuerySimulateBuy (QuerySimulateTradeRequest) returns (QuerySimulateTradeResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/simulate/buy";
  }
}

message QuerySimulateAddingLiquidityRequest {
  string token = 1;
  string amount = 2;
}

message QuerySimulateAddingLiquidityResponse {
  string amount_kcoin = 1;
  string amount_factory_token = 2;
}

message FactoryTokenBalance {
  string factory_denom_hash = 1;
  string amount_wallet = 2;
  string amount_wallet_usd = 3;
  string pool_liquidity_kcoin = 4;
  string pool_liquidity_kcoin_usd = 5;
  string pool_liquidity_factory_token = 6;
  string pool_liquidity_factory_token_usd = 7;
}

message GetFactoryTokenBalanceResponse {
  repeated FactoryTokenBalance balances = 1 [
    (gogoproto.nullable) = false
  ];
}

message GetFactoryTokenBalanceRequest {
  string address = 1;
}

message PoolLiquidityAddress {
  string factory_denom_hash = 1;
  string amount_kcoin = 2;
  string amount_factory_token = 3;
  string liquidity_value = 4;
}

message QueryPoolLiquidityAddressResponse {
  repeated PoolLiquidityAddress pools = 1 [
    (gogoproto.nullable) = false
  ];
}

message QueryPoolLiquidityAddressRequest {
  string address = 1;
}

message QuerySimulateTradeRequest {
  string denom_giving = 1;
  string denom_receiving = 2;
  string address = 3;
  string amount = 4;
}

message QuerySimulateTradeResponse {
  string amount_given = 1;
  string amount_received = 2;
  string fee = 3;
  string price = 4;
}

message QueryPoolRequest {
  string full_name = 1;
  string address = 2;
}

message QueryPoolResponse {
  string kcoin_denom = 1;
  string kcoin_amount = 2;
  string factory_amount = 3;
  string user_kcoin_amount = 4;
  string user_factory_amount = 5;
  string price = 6;
  int64 created_at = 7;
}

message QueryDenomsRequest {
  cosmos.base.query.v1beta1.PageRequest pagination = 1;
}

message FactoryDenomData {
  string admin = 1;
  string display_name = 2;
  string full_name = 3;
  string description = 4;
  string icon_hash = 5;
  string symbol = 6;
  string exponent = 7;
  string supply = 8;
  bool has_pool = 9;
  bool mintable = 10;
}

message QueryDenomsResponse {
  repeated FactoryDenomData denoms = 1;
  cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

message QueryParamsRequest {}

message QueryParamsResponse {
  Params params = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}