syntax = "proto3";
package kopi.tokenfactory;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "cosmos/base/query/v1beta1/pagination.proto";
import "kopi/tokenfactory/params.proto";
import "kopi/tokenfactory/denoms.proto";
import "kopi/tokenfactory/offer.proto";
import "kopi/tokenfactory/vesting.proto";

option go_package = "github.com/kopi-money/kopi/x/tokenfactory/types";

// Query defines the gRPC querier service.
service Query {
  // Parameters queries the parameters of the module.
  rpc QueryParams(QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/params";
  }

  rpc QueryCategories (QueryCategoriesRequest) returns (QueryCategoriesResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/categories";
  }

  rpc QueryCreationNameExists (QueryCreationNameExistsQuery) returns (QueryCreationExistsResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/creation/name";
  }

  rpc QueryCreationSymbolExists (QueryCreationSymbolExistsQuery) returns (QueryCreationExistsResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/creation/symbol";
  }

  rpc QueryDenoms (QueryDenomsRequest) returns (QueryDenomsResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/denoms";
  }

  rpc QueryPool (QueryPoolRequest) returns (QueryPoolResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/denoms/pool";
  }

  rpc QueryDistribution (QueryDistributionRequest) returns (QueryDistributionResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/distribution/by_denom";
  }

  rpc QueryFactoryTokenBalance (GetFactoryTokenBalanceRequest) returns (GetFactoryTokenBalanceResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/balance/{address}";
  }

  rpc QueryPoolLiquidityAddress (QueryPoolLiquidityAddressRequest) returns (QueryPoolLiquidityAddressResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/denoms/pool/address/{address}";
  }

  rpc QueryPoolLiquidityAddressByDenom (QueryPoolLiquidityAddressRequestByDenom) returns (PoolLiquidityAddress) {
    option (google.api.http).get = "/kopi/tokenfactory/denoms/pool/address/{address}/by_denom";
  }

  rpc QuerySimulateAddingLiquidityKCoin (QuerySimulateAddingLiquidityRequest) returns (QuerySimulateAddingLiquidityResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/denoms/pool/add/kcoin";
  }

  rpc QuerySimulateAddingLiquidityFactoryToken (QuerySimulateAddingLiquidityRequest) returns (QuerySimulateAddingLiquidityResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/denoms/pool/add/factory";
  }

  rpc QueryPoolLiquidityDistribution (QueryPoolLiquidityDistributionRequest) returns (QueryPoolLiquidityDistributionResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/denoms/pool/distribution";
  }

  rpc QueryUSDValue (QueryUSDValueRequest) returns (QueryUSDValueResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/denoms/pool/usd";
  }

  rpc QuerySimulateSell (QuerySimulateTradeRequest) returns (QuerySimulateTradeResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/simulate/sell";
  }

  rpc QuerySimulateBuy (QuerySimulateTradeRequest) returns (QuerySimulateTradeResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/simulate/buy";
  }

  rpc QueryVestings (QueryVestingsRequest) returns (QueryVestingsResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/vestings";
  }

  rpc QueryOffers (QueryOffersRequest) returns (QueryOffersResponse) {
    option (google.api.http).get = "/kopi/tokenfactory/offers";
  }
}

message QueryUSDValueRequest {
  string full_name = 1;
  string amount = 2;
}

message QueryUSDValueResponse {
  string value_usd = 1;
}

message LiquidityProvider {
  string address = 1;
  string amount_kcoin = 2;
  string amount_factory = 3;
}

message QueryPoolLiquidityDistributionResponse {
  repeated LiquidityProvider providers = 1 [
    (gogoproto.nullable) = false
  ];

  string amount_kcoin = 2;
  string amount_factory = 3;
}

message QueryPoolLiquidityDistributionRequest {
  string full_name = 1;
}

message QueryCreationExistsResponse {
  bool exists = 1;
}

message QueryCreationNameExistsQuery {
  string name = 1;
}

message QueryCreationSymbolExistsQuery {
  string symbol = 1;
}

message QueryOffersResponse {
  repeated Offer offers = 1 [
    (gogoproto.nullable) = false
  ];
}

message QueryOffersRequest {
  string full_name = 1;
  string address = 2;
}

message QueryDistributionResponse {
  string total_supply = 1;
  string admin = 2;
  string pool = 3;
  string vested = 4;
  string offered = 5;
  string unlocking = 6;
  string wallets = 7;

  string share_admin = 8;
  string share_pool = 9;
  string share_vested = 10;
  string share_offered = 11;
  string share_unlocking = 12;
  string share_wallets = 13;
}

message QueryDistributionRequest {
  string full_name = 1;
}

message QueryVestingsResponse {
  repeated Vesting vestings = 1 [
    (gogoproto.nullable) = false
  ];
}

message QueryVestingsRequest {
  string full_name = 1;
  string address = 2;
}

message CategoryResponse {
  uint64 index = 1;
  string name = 2;
  string creation_price = 3;
}

message QueryCategoriesResponse {
  repeated CategoryResponse categories = 1 [
    (gogoproto.nullable) = false
  ];
}

message QueryCategoriesRequest {
}

message QueryPoolLiquidityAddressRequestByDenom {
  string address = 1;
  string full_name = 2;
}

message QuerySimulateAddingLiquidityRequest {
  string token = 1;
  string amount = 2;
}

message QuerySimulateAddingLiquidityResponse {
  string amount_kcoin = 1;
  string amount_factory_token = 2;
}

message FactoryTokenBalance {
  string factory_denom_hash = 1;
  string kcoin = 2;
  string amount_wallet = 3;
  string amount_wallet_usd = 4;
  string pool_liquidity_kcoin = 5;
  string pool_liquidity_kcoin_usd = 6;
  string pool_liquidity_factory_token = 7;
  string pool_liquidity_factory_token_usd = 8;
  string amount_vested = 9;
  string amount_vested_usd = 10;
}

message DEXTokenBalance {
  string denom = 1;
  string amount = 2;
  string amount_usd = 3;
}

message GetFactoryTokenBalanceResponse {
  repeated FactoryTokenBalance factory = 1 [
    (gogoproto.nullable) = false
  ];
  repeated DEXTokenBalance dex = 2 [
    (gogoproto.nullable) = false
  ];
}

message GetFactoryTokenBalanceRequest {
  string address = 1;
}

message PoolLiquidityAddress {
  string factory_denom_hash = 1;
  string amount_kcoin = 2;
  string amount_factory_token = 3;
  string liquidity_value = 4;
}

message QueryPoolLiquidityAddressResponse {
  repeated PoolLiquidityAddress pools = 1 [
    (gogoproto.nullable) = false
  ];
}

message QueryPoolLiquidityAddressRequest {
  string address = 1;
}

message QuerySimulateTradeRequest {
  string denom_giving = 1;
  string denom_receiving = 2;
  string address = 3;
  string amount = 4;
}

message QuerySimulateTradeResponse {
  string amount_given = 1;
  string amount_given_usd = 2;
  string amount_received = 3;
  string amount_received_usd = 4;
  string fee = 5;
  string price = 6;
  string price_kcoin = 7;
}

message QueryPoolRequest {
  string full_name = 1;
  string address = 2;
}

message QueryPoolResponse {
  string kcoin_denom = 1;
  string kcoin_amount = 2;
  string factory_amount = 3;
  string user_kcoin_amount = 4;
  string user_factory_amount = 5;
  string price = 6;
  string marketcap = 7;
  string marketcap_usd = 8;
  string trade_fee = 9;
  uint64 unlock_period = 10;
  int64 created_at = 11;
}

message QueryDenomsRequest {
  cosmos.base.query.v1beta1.PageRequest pagination = 1;
}

message FactoryDenomData {
  string admin = 1;
  string display_name = 2;
  string full_name = 3;
  string description = 4;
  string website = 5;
  string icon_hash = 6;
  string symbol = 7;
  string exponent = 8;
  string supply = 9;
  uint64 category_index = 10;
  bool has_pool = 11;
  bool mintable = 12;
}

message QueryDenomsResponse {
  cosmos.base.query.v1beta1.PageResponse pagination = 1;
  repeated FactoryDenomData denoms = 2 [
    (gogoproto.nullable) = false
  ];
}

message QueryParamsRequest {}

message QueryParamsResponse {
  Params params = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}