syntax = "proto3";
package kopi.tokenfactory;

import "amino/amino.proto";
import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "kopi/tokenfactory/params.proto";

option go_package = "github.com/kopi-money/kopi/x/tokenfactory/types";

// Msg defines the Msg service.
service Msg {
  option (cosmos.msg.v1.service) = true;

  rpc UpdateMinimumUnlock(MsgUpdateMinimumUnlock)     returns (Void);
  rpc UpdateFeeAmount(MsgUpdateFeeAmount)             returns (Void);
  rpc UpdateReserveFee(MsgUpdateReserveFee)           returns (Void);
  rpc UpdateMinimumPoolSize(MsgUpdateMinimumPoolSize) returns (Void);

  rpc CreateDenom(MsgCreateDenom)                                 returns (MsgCreateDenomResponse);
  rpc MintDenom(MsgMintDenom)                                     returns (Void);
  rpc BurnDenom(MsgBurnDenom)                                     returns (Void);
  rpc ChangeAdmin(MsgChangeAdmin)                                 returns (Void);
  rpc UpdateIconHash(MsgUpdateIconHash)                           returns (Void);
  rpc Buyback(MsgBuyback)                                         returns (Void);
  rpc DisableMinting(MsgDisableMinting)                           returns (Void);
  rpc UpdateDescription(MsgUpdateDescription)                     returns (Void);
  rpc UpdateLiquidityPoolSettings(MsgUpdateLiquidityPoolSettings) returns (Void);

  rpc CreatePool(MsgCreatePool)           returns (Void);
  rpc AddLiquidity(MsgAddLiquidity)       returns (Void);
  rpc UnlockLiquidity(MsgUnlockLiquidity) returns (Void);
  rpc DissolvePool(MsgDissolvePool)       returns (Void);

  rpc Buy(MsgBuy) returns (MsgTradeResponse);
  rpc Sell(MsgSell) returns (MsgTradeResponse);
}

message MsgUpdateMinimumUnlock {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/tokenfactory/MsgUpdateMinimumUnlock";

  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  int64 minimum_unlock = 2;
}

message MsgUpdateReserveFee {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/tokenfactory/MsgUpdateReserveFee";

  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string reserve_fee = 2;
}

message MsgUpdateMinimumPoolSize {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/tokenfactory/MsgUpdateMinimumPoolSize";

  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string minimum_pool_size = 2;
}

message MsgUpdateFeeAmount {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/tokenfactory/MsgUpdateFeeAmount";

  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string fee_amount = 2;
}

message MsgCreateDenomResponse {
  string display_name = 1;
  string full_name = 2;
}

message MsgTradeResponse {
  string amount_given_gross = 1;
  string amount_given_net = 2;
  string amount_received_gross = 3;
  string amount_received_net = 4;
  string fee = 5;
  string fee_pool = 6;
  string fee_reserve = 7;
  string price = 8;
}

message MsgUpdateDescription {
  option (cosmos.msg.v1.signer) = "creator";
  string creator = 1;

  string full_factory_denom_name = 2;
  string description = 3;
}

message MsgDisableMinting {
  option (cosmos.msg.v1.signer) = "creator";
  string creator = 1;

  string full_factory_denom_name = 2;
}

message MsgBuy {
  option (cosmos.msg.v1.signer) = "creator";
  string creator = 1;

  string full_factory_denom_name = 2;
  string denom_giving = 3;
  string denom_receiving = 4;
  string amount = 5;
  string max_price = 6;
  bool allow_incomplete = 7;
}

message MsgSell {
  option (cosmos.msg.v1.signer) = "creator";
  string creator = 1;

  string full_factory_denom_name = 2;
  string denom_giving = 3;
  string denom_receiving = 4;
  string amount = 5;
  string max_price = 6;
  bool allow_incomplete = 7;
}

message MsgAddLiquidity {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string full_factory_denom_name = 2;

  string factory_denom_amount = 3;
}

message MsgUnlockLiquidity {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string full_factory_denom_name = 2;

  string factory_denom_amount = 3;
}

message MsgCreatePool {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string full_factory_denom_name = 2;
  string k_coin = 3;

  string factory_denom_amount = 4;
  string k_coin_amount = 5;

  string pool_fee = 6;
  uint64 unlock_in_seconds = 7;
}

message MsgDissolvePool {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string full_factory_denom_name = 2;
}

message MsgBuyback {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string full_factory_denom_name = 2;
  string buyback_amount = 3;
}

message Void {}

message MsgCreateDenom {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string name = 2;
  string icon_hash = 3;
  string description = 4;
  string symbol = 5;
  int64  initial_supply = 6;
  uint64 exponent = 7;
}

message MsgMintDenom {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string full_factory_denom_name = 2;
  string amount = 3;
  string target_address = 4;
}

message MsgBurnDenom {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string full_factory_denom_name = 2;
  string amount = 3;
}

message MsgChangeAdmin {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string full_factory_denom_name = 2;
  string new_admin = 3;
}

message MsgUpdateIconHash {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string full_factory_denom_name = 2;
  string icon_hash = 3;
}

message MsgUpdateLiquidityPoolSettings {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string full_factory_denom_name = 2;
  string pool_fee = 3;
  uint64 unlock_in_seconds = 4;
}