syntax = "proto3";
package kopi.tokenfactory;

import "google/protobuf/timestamp.proto";
import "gogoproto/gogo.proto";

option go_package = "github.com/kopi-money/kopi/x/tokenfactory/types";

message LiquidityUnlocking {
  uint64 index = 1;
  string factory_denom_hash = 2;
  string k_coin = 3;
  string address = 4;

  google.protobuf.Timestamp created_at = 5 [
    (gogoproto.stdtime) = true,
    (gogoproto.nullable) = true,
    (gogoproto.moretags) = "yaml:\"created_at\""
  ];

  bytes factory_denom_amount = 6 [
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false
  ];

  bytes k_coin_amount = 7 [
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false
  ];
}