syntax = "proto3";
package kopi.dex;

import "gogoproto/gogo.proto";
import "google/protobuf/wrappers.proto";

option go_package = "github.com/kopi-money/kopi/x/dex/types";

message GenesisLiquidity {
  uint64 index = 1;
  string address = 2;
  bytes amount = 3 [
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false
  ];
  uint64 position_index = 4;
  string denom = 5;
}

message Liquidity {
  uint64 index = 1;
  string address = 2;
  bytes amount = 3 [
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false
  ];

  uint64 position_index = 4;
}

message GenesisLiquidityPositions {
  string address = 1;
  uint64 position_index = 2;
  bool auto_compound = 3;
}

message LiquidityPosition {
  bool auto_compound = 1;
}
