syntax = "proto3";
package kopi.dex;

import "gogoproto/gogo.proto";

option go_package = "github.com/kopi-money/kopi/x/dex/types";

message LiquidityPair {
  TradeLiquidity base = 1 [
    (gogoproto.nullable)   = false
  ];

  TradeLiquidity other = 2 [
    (gogoproto.nullable)   = false
  ];
}

message TradeLiquidity {
  bytes actual = 1 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable)   = false
  ];

  bytes trade_value = 2 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable)   = false
  ];

  bytes trade_value_base = 3 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable)   = false
  ];

  bytes minimum_trade_value_base = 4 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable)   = false
  ];

  bytes virtual = 5 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable)   = false
  ];
}
