syntax = "proto3";
package kopi.dex;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "kopi/dex/discount_level.proto";

option go_package = "github.com/kopi-money/kopi/x/dex/types";

// Params defines the parameters for the module.
message Params {
  option (amino.name) = "kopi/x/dex/Params";
  option (gogoproto.equal) = true;

  bytes trade_fee = 1 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable)   = false
  ];

  bytes order_fee = 2 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable)   = false
  ];

  bytes reserve_share = 3 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable)   = false
  ];

  bytes price_increasing_factor = 4 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable)   = false
  ];

  bytes trade_amount_decay = 5 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable)   = false
  ];

  repeated DiscountLevel discount_levels = 6 [
    (gogoproto.nullable) = false
  ];

  uint64 max_order_life = 7;

  bytes trade_base_value = 8 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable)   = false,
    deprecated = true
  ];

  uint64 epoch_length = 9;

  bytes liquidity_change_decay_from_deposits = 10 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable)   = false
  ];

  int64 minimum_liquidity_lock_in_blocks = 11;
}