syntax = "proto3";

package kopi.dex;

import "amino/amino.proto";
import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "kopi/dex/order.proto";
import "kopi/dex/params.proto";
import "kopi/dex/discount_level.proto";

// this line is used by starport scaffolding # proto/tx/import

option go_package = "github.com/kopi-money/kopi/x/dex/types";

// Msg defines the Msg service.
service Msg {
  option (cosmos.msg.v1.service) = true;

  rpc AddLiquidity    (MsgAddLiquidity) returns (MsgAddLiquidityResponse);
  rpc RemoveLiquidity (MsgRemoveLiquidity) returns (MsgRemoveLiquidityResponse);
  rpc RemoveAllLiquidityForDenom (MsgRemoveAllLiquidityForDenom) returns (MsgRemoveLiquidityResponse);
  rpc ChangePayout    (MsgChangePayout) returns (Void);
  rpc Sell            (MsgSell) returns (MsgTradeResponse);
  rpc Buy             (MsgBuy) returns (MsgTradeResponse);

  // this line is used by starport scaffolding # proto/tx/rpc
  rpc AddOrder                   (MsgAddOrder) returns (Order);
  rpc RemoveOrder                (MsgRemoveOrder) returns (Void);
  rpc RemoveOrders               (MsgRemoveOrders) returns (Void);
  rpc UpdateOrder                (MsgUpdateOrder) returns (Order);

  rpc UpdateTradeFee              (MsgUpdateTradeFee) returns (Void);
  rpc UpdateOrderFee              (MsgUpdateOrderFee) returns (Void);
  rpc UpdateReserveShare          (MsgUpdateReserveShare) returns (Void);
  rpc UpdateVirtualLiquidityDecay (MsgUpdateVirtualLiquidityDecay) returns (Void);
  rpc UpdateMaxOrderLife          (MsgUpdateMaxOrderLife) returns (Void);
  rpc UpdateTradeAmountDecay      (MsgUpdateTradeAmountDecay) returns (Void);
  rpc UpdateDiscountLevels        (MsgUpdateDiscountLevels) returns (Void);
  rpc UpdateEpochLength           (MsgUpdateEpochLength) returns (Void);
  rpc UpdateLiquidityChangeDecay  (MsgUpdateLiquidityChangeDecay) returns (Void);
  rpc RemoveDexDenom              (MsgRemoveDexDenom) returns (Void);
}

message MsgUpdateEpochLength {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/denominations/MsgUpdateEpochLength";
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  string epoch_length = 2;
}

message MsgRemoveDexDenom {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/denominations/MsgRemoveDexDenom";
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  string name = 2;
}

message MsgUpdateDiscountLevels {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/dex/MsgUpdateDiscountLevels";
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  repeated DiscountLevel discount_levels = 2 [
    (gogoproto.nullable) = false
  ];
}

message MsgUpdateTradeAmountDecay {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/dex/MsgUpdateTradeAmountDecay";
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  string trade_amount_decay = 2;
}

message MsgUpdateMaxOrderLife {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/dex/MsgUpdateMaxOrderLife";
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  uint64 max_order_life = 2;
}

message MsgUpdateVirtualLiquidityDecay {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/dex/MsgUpdateVirtualLiquidityDecay";
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  string virtual_liquidity_decay = 2;
}

message MsgUpdateReserveShare {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/dex/MsgUpdateReserveShare";
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  string reserve_share = 2;
}

message MsgUpdateLiquidityChangeDecay {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/dex/MsgUpdateLiquidityChangeDecay";
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  string liquidity_change_decay = 2;
}

message MsgUpdateTradeFee {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/dex/MsgUpdateTradeFee";
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  string trade_fee = 2;
}

message MsgUpdateOrderFee {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/dex/MsgUpdateOrderFee";
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  string order_fee = 2;
}

message Void {}

message MsgUpdateParamsResponse {}

message MsgChangePayout {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  uint64 position_index = 2;
  bool auto_compound = 3;
}

message MsgAddLiquidity {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string denom = 2;
  string amount = 3;
  bool auto_compound = 4;
}

message MsgAddLiquidityResponse {}

message MsgRemoveLiquidity {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string withdraw_denom = 2;
  string payout_denom = 3;
  string amount = 4;
  string position_index = 5;
}

message MsgRemoveLiquidityResponse {}

message MsgBuy {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string denom_giving = 2;
  string denom_receiving = 3;
  string amount = 4;
  string max_price = 5;
  string minimum_trade_amount = 6;

}

message MsgSell {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string denom_giving = 2;
  string denom_receiving = 3;
  string amount = 4;
  string max_price = 5;
  string minimum_trade_amount = 6;
}

message MsgTradeResponse {
  string amount_given = 1;
  string amount_received = 2;
}

// this line is used by starport scaffolding # proto/tx/message
message MsgRemoveAllLiquidityForDenom {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string withdraw_denom = 2;
  string payout_denom = 3;
}

message MsgAddOrder {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string denom_giving = 2;
  string denom_receiving = 3;
  string amount = 4;
  string trade_amount = 5;
  string max_price = 6;
  uint64 blocks = 7;
  uint64 interval = 8;
  bool allow_incomplete = 9;
  bool is_buy_order = 10;
}

message MsgRemoveOrder {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  uint64 index = 2;
}

message MsgRemoveOrders {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
}

message MsgUpdateOrder {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  uint64 index = 2;

  string amount = 3;
  string trade_amount = 4;
  string max_price = 5;
}
