syntax = "proto3";
package kopi.swap;

import "amino/amino.proto";
import "gogoproto/gogo.proto";

option go_package = "github.com/kopi-money/kopi/x/swap/types";

// Params defines the parameters for the module.
message Params {
  option (amino.name) = "kopi/x/swap/Params";
  option (gogoproto.equal) = true;

  bytes burn_threshold = 1 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable)   = false
  ];

  bytes mint_threshold = 2 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable)   = false
  ];

  bytes staking_share = 3 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable)   = false
  ];

  bytes parity_factor = 4 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable)   = false
  ];
}