// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kopi/denominations/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DexDenom struct {
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Exponent          uint64                 `protobuf:"varint,2,opt,name=exponent,proto3" json:"exponent,omitempty"`
	MinTradeLiquidity cosmossdk_io_math.Int  `protobuf:"bytes,3,opt,name=min_trade_liquidity,json=minTradeLiquidity,proto3,customtype=cosmossdk.io/math.Int" json:"min_trade_liquidity"`
	MinOrderSize      cosmossdk_io_math.Int  `protobuf:"bytes,4,opt,name=min_order_size,json=minOrderSize,proto3,customtype=cosmossdk.io/math.Int" json:"min_order_size"`
	MinDexLiquidity   *cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=min_dex_liquidity,json=minDexLiquidity,proto3,customtype=cosmossdk.io/math.Int" json:"min_dex_liquidity,omitempty"`
}

func (m *DexDenom) Reset()         { *m = DexDenom{} }
func (m *DexDenom) String() string { return proto.CompactTextString(m) }
func (*DexDenom) ProtoMessage()    {}
func (*DexDenom) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a3f835420dd58e1, []int{0}
}
func (m *DexDenom) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DexDenom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DexDenom.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DexDenom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DexDenom.Merge(m, src)
}
func (m *DexDenom) XXX_Size() int {
	return m.Size()
}
func (m *DexDenom) XXX_DiscardUnknown() {
	xxx_messageInfo_DexDenom.DiscardUnknown(m)
}

var xxx_messageInfo_DexDenom proto.InternalMessageInfo

func (m *DexDenom) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DexDenom) GetExponent() uint64 {
	if m != nil {
		return m.Exponent
	}
	return 0
}

type KCoin struct {
	DexDenom      string                `protobuf:"bytes,1,opt,name=dex_denom,json=dexDenom,proto3" json:"dex_denom,omitempty"`
	References    []string              `protobuf:"bytes,2,rep,name=references,proto3" json:"references,omitempty"`
	MaxSupply     cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=max_supply,json=maxSupply,proto3,customtype=cosmossdk.io/math.Int" json:"max_supply"`
	MaxMintAmount cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=max_mint_amount,json=maxMintAmount,proto3,customtype=cosmossdk.io/math.Int" json:"max_mint_amount"`
	MaxBurnAmount cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=max_burn_amount,json=maxBurnAmount,proto3,customtype=cosmossdk.io/math.Int" json:"max_burn_amount"`
}

func (m *KCoin) Reset()         { *m = KCoin{} }
func (m *KCoin) String() string { return proto.CompactTextString(m) }
func (*KCoin) ProtoMessage()    {}
func (*KCoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a3f835420dd58e1, []int{1}
}
func (m *KCoin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KCoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KCoin.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KCoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KCoin.Merge(m, src)
}
func (m *KCoin) XXX_Size() int {
	return m.Size()
}
func (m *KCoin) XXX_DiscardUnknown() {
	xxx_messageInfo_KCoin.DiscardUnknown(m)
}

var xxx_messageInfo_KCoin proto.InternalMessageInfo

func (m *KCoin) GetDexDenom() string {
	if m != nil {
		return m.DexDenom
	}
	return ""
}

func (m *KCoin) GetReferences() []string {
	if m != nil {
		return m.References
	}
	return nil
}

type ArbitrageDenom struct {
	DexDenom                  string                      `protobuf:"bytes,1,opt,name=dex_denom,json=dexDenom,proto3" json:"dex_denom,omitempty"`
	KCoin                     string                      `protobuf:"bytes,2,opt,name=k_coin,json=kCoin,proto3" json:"k_coin,omitempty"`
	CAsset                    string                      `protobuf:"bytes,3,opt,name=c_asset,json=cAsset,proto3" json:"c_asset,omitempty"`
	BuyThreshold              cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=buy_threshold,json=buyThreshold,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"buy_threshold"`
	SellThreshold             cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=sell_threshold,json=sellThreshold,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"sell_threshold"`
	BuyTradeAmount            cosmossdk_io_math.Int       `protobuf:"bytes,6,opt,name=buy_trade_amount,json=buyTradeAmount,proto3,customtype=cosmossdk.io/math.Int" json:"buy_trade_amount"`
	SellTradeAmount           cosmossdk_io_math.Int       `protobuf:"bytes,7,opt,name=sell_trade_amount,json=sellTradeAmount,proto3,customtype=cosmossdk.io/math.Int" json:"sell_trade_amount"`
	RedemptionFee             cosmossdk_io_math.LegacyDec `protobuf:"bytes,8,opt,name=redemption_fee,json=redemptionFee,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"redemption_fee"`
	RedemptionFeeReserveShare cosmossdk_io_math.LegacyDec `protobuf:"bytes,9,opt,name=redemption_fee_reserve_share,json=redemptionFeeReserveShare,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"redemption_fee_reserve_share"`
}

func (m *ArbitrageDenom) Reset()         { *m = ArbitrageDenom{} }
func (m *ArbitrageDenom) String() string { return proto.CompactTextString(m) }
func (*ArbitrageDenom) ProtoMessage()    {}
func (*ArbitrageDenom) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a3f835420dd58e1, []int{2}
}
func (m *ArbitrageDenom) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ArbitrageDenom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ArbitrageDenom.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ArbitrageDenom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArbitrageDenom.Merge(m, src)
}
func (m *ArbitrageDenom) XXX_Size() int {
	return m.Size()
}
func (m *ArbitrageDenom) XXX_DiscardUnknown() {
	xxx_messageInfo_ArbitrageDenom.DiscardUnknown(m)
}

var xxx_messageInfo_ArbitrageDenom proto.InternalMessageInfo

func (m *ArbitrageDenom) GetDexDenom() string {
	if m != nil {
		return m.DexDenom
	}
	return ""
}

func (m *ArbitrageDenom) GetKCoin() string {
	if m != nil {
		return m.KCoin
	}
	return ""
}

func (m *ArbitrageDenom) GetCAsset() string {
	if m != nil {
		return m.CAsset
	}
	return ""
}

type CollateralDenom struct {
	DexDenom   string                      `protobuf:"bytes,1,opt,name=dex_denom,json=dexDenom,proto3" json:"dex_denom,omitempty"`
	Ltv        cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=ltv,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"ltv"`
	MaxDeposit cosmossdk_io_math.Int       `protobuf:"bytes,3,opt,name=max_deposit,json=maxDeposit,proto3,customtype=cosmossdk.io/math.Int" json:"max_deposit"`
}

func (m *CollateralDenom) Reset()         { *m = CollateralDenom{} }
func (m *CollateralDenom) String() string { return proto.CompactTextString(m) }
func (*CollateralDenom) ProtoMessage()    {}
func (*CollateralDenom) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a3f835420dd58e1, []int{3}
}
func (m *CollateralDenom) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CollateralDenom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CollateralDenom.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CollateralDenom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralDenom.Merge(m, src)
}
func (m *CollateralDenom) XXX_Size() int {
	return m.Size()
}
func (m *CollateralDenom) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralDenom.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralDenom proto.InternalMessageInfo

func (m *CollateralDenom) GetDexDenom() string {
	if m != nil {
		return m.DexDenom
	}
	return ""
}

type CAsset struct {
	DexDenom        string                      `protobuf:"bytes,1,opt,name=dex_denom,json=dexDenom,proto3" json:"dex_denom,omitempty"`
	BaseDexDenom    string                      `protobuf:"bytes,2,opt,name=base_dex_denom,json=baseDexDenom,proto3" json:"base_dex_denom,omitempty"`
	DexFeeShare     cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=dex_fee_share,json=dexFeeShare,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"dex_fee_share"`
	BorrowLimit     cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=borrow_limit,json=borrowLimit,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"borrow_limit"`
	MinimumLoanSize cosmossdk_io_math.Int       `protobuf:"bytes,5,opt,name=minimum_loan_size,json=minimumLoanSize,proto3,customtype=cosmossdk.io/math.Int" json:"minimum_loan_size"`
}

func (m *CAsset) Reset()         { *m = CAsset{} }
func (m *CAsset) String() string { return proto.CompactTextString(m) }
func (*CAsset) ProtoMessage()    {}
func (*CAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a3f835420dd58e1, []int{4}
}
func (m *CAsset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CAsset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CAsset.Merge(m, src)
}
func (m *CAsset) XXX_Size() int {
	return m.Size()
}
func (m *CAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_CAsset.DiscardUnknown(m)
}

var xxx_messageInfo_CAsset proto.InternalMessageInfo

func (m *CAsset) GetDexDenom() string {
	if m != nil {
		return m.DexDenom
	}
	return ""
}

func (m *CAsset) GetBaseDexDenom() string {
	if m != nil {
		return m.BaseDexDenom
	}
	return ""
}

type StrategyDenoms struct {
	ArbitrageDenoms []ArbitrageDenom `protobuf:"bytes,5,rep,name=arbitrage_denoms,json=arbitrageDenoms,proto3" json:"arbitrage_denoms"`
}

func (m *StrategyDenoms) Reset()         { *m = StrategyDenoms{} }
func (m *StrategyDenoms) String() string { return proto.CompactTextString(m) }
func (*StrategyDenoms) ProtoMessage()    {}
func (*StrategyDenoms) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a3f835420dd58e1, []int{5}
}
func (m *StrategyDenoms) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StrategyDenoms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StrategyDenoms.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StrategyDenoms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategyDenoms.Merge(m, src)
}
func (m *StrategyDenoms) XXX_Size() int {
	return m.Size()
}
func (m *StrategyDenoms) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategyDenoms.DiscardUnknown(m)
}

var xxx_messageInfo_StrategyDenoms proto.InternalMessageInfo

func (m *StrategyDenoms) GetArbitrageDenoms() []ArbitrageDenom {
	if m != nil {
		return m.ArbitrageDenoms
	}
	return nil
}

type FactoryPoolDenom struct {
	Denom           string                `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	MinimumPoolSize cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=minimum_pool_size,json=minimumPoolSize,proto3,customtype=cosmossdk.io/math.Int" json:"minimum_pool_size"`
	MoveThreshold   cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=move_threshold,json=moveThreshold,proto3,customtype=cosmossdk.io/math.Int" json:"move_threshold"`
}

func (m *FactoryPoolDenom) Reset()         { *m = FactoryPoolDenom{} }
func (m *FactoryPoolDenom) String() string { return proto.CompactTextString(m) }
func (*FactoryPoolDenom) ProtoMessage()    {}
func (*FactoryPoolDenom) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a3f835420dd58e1, []int{6}
}
func (m *FactoryPoolDenom) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FactoryPoolDenom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FactoryPoolDenom.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FactoryPoolDenom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FactoryPoolDenom.Merge(m, src)
}
func (m *FactoryPoolDenom) XXX_Size() int {
	return m.Size()
}
func (m *FactoryPoolDenom) XXX_DiscardUnknown() {
	xxx_messageInfo_FactoryPoolDenom.DiscardUnknown(m)
}

var xxx_messageInfo_FactoryPoolDenom proto.InternalMessageInfo

func (m *FactoryPoolDenom) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// Params defines the parameters for the module.
type Params struct {
	DexDenoms         []DexDenom         `protobuf:"bytes,1,rep,name=dex_denoms,json=dexDenoms,proto3" json:"dex_denoms"`
	KCoins            []KCoin            `protobuf:"bytes,2,rep,name=k_coins,json=kCoins,proto3" json:"k_coins"`
	CAssets           []CAsset           `protobuf:"bytes,3,rep,name=c_assets,json=cAssets,proto3" json:"c_assets"`
	CollateralDenoms  []CollateralDenom  `protobuf:"bytes,4,rep,name=collateral_denoms,json=collateralDenoms,proto3" json:"collateral_denoms"`
	StrategyDenoms    StrategyDenoms     `protobuf:"bytes,5,opt,name=strategy_denoms,json=strategyDenoms,proto3" json:"strategy_denoms"`
	FactoryPoolDenoms []FactoryPoolDenom `protobuf:"bytes,6,rep,name=factory_pool_denoms,json=factoryPoolDenoms,proto3" json:"factory_pool_denoms"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a3f835420dd58e1, []int{7}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetDexDenoms() []DexDenom {
	if m != nil {
		return m.DexDenoms
	}
	return nil
}

func (m *Params) GetKCoins() []KCoin {
	if m != nil {
		return m.KCoins
	}
	return nil
}

func (m *Params) GetCAssets() []CAsset {
	if m != nil {
		return m.CAssets
	}
	return nil
}

func (m *Params) GetCollateralDenoms() []CollateralDenom {
	if m != nil {
		return m.CollateralDenoms
	}
	return nil
}

func (m *Params) GetStrategyDenoms() StrategyDenoms {
	if m != nil {
		return m.StrategyDenoms
	}
	return StrategyDenoms{}
}

func (m *Params) GetFactoryPoolDenoms() []FactoryPoolDenom {
	if m != nil {
		return m.FactoryPoolDenoms
	}
	return nil
}

func init() {
	proto.RegisterType((*DexDenom)(nil), "kopi.denominations.DexDenom")
	proto.RegisterType((*KCoin)(nil), "kopi.denominations.KCoin")
	proto.RegisterType((*ArbitrageDenom)(nil), "kopi.denominations.ArbitrageDenom")
	proto.RegisterType((*CollateralDenom)(nil), "kopi.denominations.CollateralDenom")
	proto.RegisterType((*CAsset)(nil), "kopi.denominations.CAsset")
	proto.RegisterType((*StrategyDenoms)(nil), "kopi.denominations.StrategyDenoms")
	proto.RegisterType((*FactoryPoolDenom)(nil), "kopi.denominations.FactoryPoolDenom")
	proto.RegisterType((*Params)(nil), "kopi.denominations.Params")
}

func init() { proto.RegisterFile("kopi/denominations/params.proto", fileDescriptor_6a3f835420dd58e1) }

var fileDescriptor_6a3f835420dd58e1 = []byte{
	// 998 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcf, 0x4f, 0x1b, 0x47,
	0x14, 0x66, 0xfd, 0x0b, 0xfc, 0x00, 0x1b, 0x26, 0x89, 0xea, 0x90, 0xd4, 0x20, 0x27, 0x07, 0x2e,
	0xb5, 0xab, 0x54, 0x95, 0xaa, 0xb6, 0xaa, 0x04, 0xb8, 0xa4, 0x50, 0xa2, 0xa6, 0x26, 0xea, 0x21,
	0x97, 0xd5, 0x78, 0xf7, 0x61, 0x46, 0xec, 0xcc, 0xb8, 0x33, 0x63, 0x6a, 0xe7, 0xaf, 0xc8, 0xb1,
	0xbd, 0xf5, 0x52, 0xf5, 0x6f, 0xc8, 0x7f, 0x90, 0x5b, 0x73, 0xac, 0x7a, 0x88, 0x2a, 0xf8, 0x47,
	0xa2, 0x99, 0x59, 0x1b, 0x9b, 0x38, 0xd1, 0x72, 0x81, 0xdd, 0xd1, 0xfb, 0xbe, 0x79, 0xef, 0xf3,
	0x37, 0xdf, 0x2c, 0x6c, 0x9e, 0xc9, 0x3e, 0x6b, 0xc5, 0x28, 0x24, 0x67, 0x82, 0x1a, 0x26, 0x85,
	0x6e, 0xf5, 0xa9, 0xa2, 0x5c, 0x37, 0xfb, 0x4a, 0x1a, 0x49, 0x88, 0x2d, 0x68, 0xce, 0x14, 0x6c,
	0xac, 0x53, 0xce, 0x84, 0x6c, 0xb9, 0xbf, 0xbe, 0x6c, 0xe3, 0x76, 0x4f, 0xf6, 0xa4, 0x7b, 0x6c,
	0xd9, 0xa7, 0x74, 0x75, 0x1e, 0xbb, 0xb2, 0xff, 0x53, 0xf6, 0xc6, 0x1f, 0x39, 0x58, 0x6a, 0xe3,
	0xb0, 0x6d, 0x2b, 0x08, 0x81, 0x82, 0xa0, 0x1c, 0x6b, 0xc1, 0x56, 0xb0, 0x5d, 0xee, 0xb8, 0x67,
	0xb2, 0x01, 0x4b, 0x38, 0xec, 0x4b, 0x81, 0xc2, 0xd4, 0x72, 0x5b, 0xc1, 0x76, 0xa1, 0x33, 0x79,
	0x27, 0x4f, 0xe0, 0x16, 0x67, 0x22, 0x34, 0x8a, 0xc6, 0x18, 0x26, 0xec, 0xd7, 0x01, 0x8b, 0x99,
	0x19, 0xd5, 0xf2, 0x5b, 0xc1, 0xf6, 0xca, 0xee, 0xa7, 0xaf, 0xdf, 0x6e, 0x2e, 0xfc, 0xf7, 0x76,
	0xf3, 0x4e, 0x24, 0x35, 0x97, 0x5a, 0xc7, 0x67, 0x4d, 0x26, 0x5b, 0x9c, 0x9a, 0xd3, 0xe6, 0x81,
	0x30, 0x9d, 0x75, 0xce, 0xc4, 0x33, 0x0b, 0x3c, 0x1a, 0xe3, 0xc8, 0x1e, 0x54, 0x2c, 0x9d, 0x54,
	0x31, 0xaa, 0x50, 0xb3, 0x17, 0x58, 0x2b, 0x64, 0x61, 0x5a, 0xe1, 0x4c, 0xfc, 0x64, 0x31, 0xc7,
	0xec, 0x05, 0x92, 0x03, 0xb0, 0xcc, 0x61, 0x8c, 0xc3, 0xa9, 0x8e, 0x8a, 0x13, 0x9e, 0xe0, 0xc3,
	0x3c, 0x55, 0xce, 0x44, 0x1b, 0x87, 0x93, 0x7e, 0x1a, 0x2f, 0x73, 0x50, 0xfc, 0x71, 0x4f, 0x32,
	0x41, 0xee, 0x41, 0xd9, 0x12, 0x3a, 0x1d, 0x53, 0x75, 0x96, 0xe2, 0xb1, 0x6a, 0x75, 0x00, 0x85,
	0x27, 0xa8, 0x50, 0x44, 0xa8, 0x6b, 0xb9, 0xad, 0xfc, 0x76, 0xb9, 0x33, 0xb5, 0x42, 0xbe, 0x05,
	0xe0, 0x74, 0x18, 0xea, 0x41, 0xbf, 0x9f, 0x64, 0x14, 0xa7, 0xcc, 0xe9, 0xf0, 0xd8, 0xd5, 0x93,
	0xef, 0xa1, 0x6a, 0xd1, 0x9c, 0x09, 0x13, 0x52, 0x2e, 0x07, 0xc2, 0x64, 0x53, 0x65, 0x95, 0xd3,
	0xe1, 0x13, 0x26, 0xcc, 0x8e, 0xc3, 0x8c, 0x69, 0xba, 0x03, 0x25, 0xc6, 0x34, 0xc5, 0xac, 0x34,
	0xbb, 0x03, 0x25, 0x3c, 0x4d, 0xe3, 0x55, 0x01, 0x2a, 0x3b, 0xaa, 0xcb, 0x8c, 0xa2, 0x3d, 0xf4,
	0xe3, 0x7f, 0x54, 0x9b, 0x3b, 0x50, 0x3a, 0x0b, 0x23, 0xc9, 0x84, 0xf3, 0x4e, 0xb9, 0x53, 0x3c,
	0x73, 0x7a, 0x7e, 0x02, 0x8b, 0x51, 0x48, 0xb5, 0x46, 0xe3, 0xf4, 0x28, 0x77, 0x4a, 0xd1, 0x8e,
	0x7d, 0x23, 0x3f, 0xc0, 0x6a, 0x77, 0x30, 0x0a, 0xcd, 0xa9, 0x42, 0x7d, 0x2a, 0x93, 0x38, 0x9d,
	0xf5, 0x41, 0xda, 0xe4, 0xbd, 0xf7, 0x9b, 0x3c, 0xc2, 0x1e, 0x8d, 0x46, 0x6d, 0x8c, 0x3a, 0x2b,
	0xdd, 0xc1, 0xe8, 0xd9, 0x18, 0x48, 0x0e, 0xa1, 0xa2, 0x31, 0x49, 0xa6, 0xa8, 0x8a, 0xd9, 0xa9,
	0x56, 0x2d, 0xf4, 0x8a, 0xeb, 0x31, 0xac, 0xb9, 0xae, 0x9c, 0xcf, 0x53, 0xf5, 0x4a, 0x59, 0xd4,
	0xab, 0xd8, 0x96, 0x2c, 0x2a, 0xfd, 0x15, 0x0e, 0x60, 0xdd, 0x37, 0x35, 0xcd, 0xb4, 0x98, 0x85,
	0xa9, 0xea, 0x3a, 0x9a, 0xa2, 0x3a, 0x84, 0x8a, 0xc2, 0x18, 0x79, 0xdf, 0x1e, 0xea, 0xf0, 0x04,
	0xb1, 0xb6, 0x74, 0x83, 0xf9, 0xae, 0xa0, 0xfb, 0x88, 0x24, 0x86, 0xfb, 0xb3, 0x5c, 0xa1, 0x42,
	0x8d, 0xea, 0x1c, 0x43, 0x7d, 0x4a, 0x15, 0xd6, 0xca, 0xd9, 0x99, 0xef, 0xce, 0x30, 0x77, 0x3c,
	0xcd, 0xb1, 0x65, 0x69, 0xfc, 0x15, 0x40, 0x75, 0x4f, 0x26, 0x09, 0x35, 0xa8, 0x68, 0x92, 0xc1,
	0x3c, 0x5f, 0x42, 0x3e, 0x31, 0xe7, 0xce, 0x39, 0x19, 0x77, 0xb7, 0xf5, 0xe4, 0x3b, 0x58, 0xb6,
	0x56, 0x8f, 0xb1, 0x2f, 0x35, 0x33, 0xd9, 0x0e, 0x9c, 0x3d, 0xa1, 0x6d, 0x0f, 0x68, 0xfc, 0x9d,
	0x83, 0xd2, 0x9e, 0xb7, 0xe3, 0x47, 0xdb, 0x7b, 0x08, 0x95, 0x2e, 0xd5, 0x18, 0x5e, 0x55, 0x78,
	0x8f, 0xaf, 0xd8, 0xd5, 0x49, 0xa6, 0x3e, 0x86, 0x55, 0x5b, 0x60, 0x45, 0xf5, 0x62, 0xe6, 0xb3,
	0x8f, 0xb3, 0x1c, 0xe3, 0x70, 0x1f, 0xbd, 0x7c, 0x64, 0x1f, 0x56, 0xba, 0x52, 0x29, 0xf9, 0x5b,
	0x98, 0x30, 0xce, 0xcc, 0x4d, 0x4e, 0xc6, 0xb2, 0x07, 0x1e, 0x59, 0x5c, 0x1a, 0x90, 0x8c, 0x0f,
	0x78, 0x98, 0x48, 0x2a, 0x7c, 0xd0, 0x66, 0xca, 0x82, 0x6a, 0x8a, 0x3b, 0x92, 0x54, 0xd8, 0xac,
	0x6d, 0x20, 0x54, 0x8e, 0x8d, 0xa2, 0x06, 0x7b, 0x23, 0x37, 0xac, 0x26, 0xc7, 0xb0, 0x46, 0xc7,
	0xf1, 0xe0, 0x45, 0xd1, 0xb5, 0xe2, 0x56, 0x7e, 0x7b, 0xf9, 0x51, 0xa3, 0xf9, 0xfe, 0x3d, 0xd6,
	0x9c, 0x8d, 0x92, 0xdd, 0x82, 0xdd, 0xbf, 0x53, 0xa5, 0x33, 0xab, 0xba, 0xf1, 0x2a, 0x80, 0xb5,
	0x7d, 0x1a, 0x19, 0xa9, 0x46, 0x4f, 0xa5, 0x4c, 0x9d, 0x73, 0x1b, 0x8a, 0xd3, 0x3f, 0x8b, 0x7f,
	0x99, 0x1e, 0xae, 0x2f, 0x65, 0xe2, 0x87, 0xcb, 0xdd, 0x64, 0x38, 0xbb, 0x83, 0xbb, 0x48, 0xda,
	0x50, 0xe1, 0xf2, 0x1c, 0xa7, 0x02, 0x24, 0x9f, 0x2d, 0x30, 0xe5, 0x39, 0x4e, 0xa2, 0xa3, 0xf1,
	0x4f, 0x1e, 0x4a, 0x4f, 0xdd, 0x75, 0x4e, 0x76, 0x00, 0x26, 0x56, 0xd1, 0xb5, 0xc0, 0xa9, 0x72,
	0x7f, 0x9e, 0x2a, 0x63, 0xef, 0xa4, 0x7a, 0x94, 0xc7, 0x8e, 0xd3, 0xe4, 0x2b, 0x58, 0xf4, 0x71,
	0xea, 0xef, 0x99, 0xe5, 0x47, 0x77, 0xe7, 0xe1, 0xdd, 0x9d, 0x95, 0x82, 0x4b, 0x2e, 0x70, 0x35,
	0xf9, 0x06, 0x96, 0xd2, 0xc4, 0xd5, 0xb5, 0xbc, 0x83, 0x6e, 0xcc, 0x83, 0x7a, 0xdf, 0xa7, 0xd8,
	0x45, 0x1f, 0xca, 0x9a, 0xfc, 0x02, 0xeb, 0xd1, 0xe4, 0xe0, 0x8e, 0x07, 0x28, 0x38, 0x96, 0x07,
	0x73, 0x59, 0x66, 0x4f, 0x79, 0x4a, 0xb7, 0x16, 0xcd, 0x2e, 0x6b, 0xf2, 0x33, 0x54, 0x75, 0xea,
	0x9f, 0x2b, 0xb3, 0x04, 0x1f, 0x32, 0xcb, 0xac, 0xd5, 0x52, 0xd2, 0x8a, 0x9e, 0x35, 0xe0, 0x73,
	0xb8, 0x75, 0xe2, 0xad, 0xe2, 0x0d, 0x90, 0xd2, 0x96, 0x5c, 0xb3, 0x0f, 0xe7, 0xd1, 0x5e, 0x77,
	0x56, 0x4a, 0xbc, 0x7e, 0x72, 0x6d, 0x5d, 0x7f, 0x5d, 0xf8, 0xfd, 0xcf, 0xcd, 0x85, 0xdd, 0xc3,
	0xd7, 0x17, 0xf5, 0xe0, 0xcd, 0x45, 0x3d, 0xf8, 0xff, 0xa2, 0x1e, 0xbc, 0xbc, 0xac, 0x2f, 0xbc,
	0xb9, 0xac, 0x2f, 0xfc, 0x7b, 0x59, 0x5f, 0x78, 0xfe, 0x79, 0x8f, 0x99, 0xd3, 0x41, 0xb7, 0x19,
	0x49, 0xde, 0xb2, 0x1b, 0x7d, 0xc6, 0xa5, 0xc0, 0x91, 0x7b, 0x6c, 0x0d, 0xaf, 0x7d, 0x84, 0x99,
	0x51, 0x1f, 0x75, 0xb7, 0xe4, 0x3e, 0xc2, 0xbe, 0x78, 0x17, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x76,
	0x05, 0xc6, 0x05, 0x0a, 0x00, 0x00,
}

func (m *DexDenom) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DexDenom) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DexDenom) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MinDexLiquidity != nil {
		{
			size := m.MinDexLiquidity.Size()
			i -= size
			if _, err := m.MinDexLiquidity.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintParams(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	{
		size := m.MinOrderSize.Size()
		i -= size
		if _, err := m.MinOrderSize.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.MinTradeLiquidity.Size()
		i -= size
		if _, err := m.MinTradeLiquidity.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Exponent != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.Exponent))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *KCoin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KCoin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KCoin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MaxBurnAmount.Size()
		i -= size
		if _, err := m.MaxBurnAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.MaxMintAmount.Size()
		i -= size
		if _, err := m.MaxMintAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.MaxSupply.Size()
		i -= size
		if _, err := m.MaxSupply.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.References) > 0 {
		for iNdEx := len(m.References) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.References[iNdEx])
			copy(dAtA[i:], m.References[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.References[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.DexDenom) > 0 {
		i -= len(m.DexDenom)
		copy(dAtA[i:], m.DexDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DexDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ArbitrageDenom) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ArbitrageDenom) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ArbitrageDenom) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.RedemptionFeeReserveShare.Size()
		i -= size
		if _, err := m.RedemptionFeeReserveShare.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size := m.RedemptionFee.Size()
		i -= size
		if _, err := m.RedemptionFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.SellTradeAmount.Size()
		i -= size
		if _, err := m.SellTradeAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.BuyTradeAmount.Size()
		i -= size
		if _, err := m.BuyTradeAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.SellThreshold.Size()
		i -= size
		if _, err := m.SellThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.BuyThreshold.Size()
		i -= size
		if _, err := m.BuyThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.CAsset) > 0 {
		i -= len(m.CAsset)
		copy(dAtA[i:], m.CAsset)
		i = encodeVarintParams(dAtA, i, uint64(len(m.CAsset)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.KCoin) > 0 {
		i -= len(m.KCoin)
		copy(dAtA[i:], m.KCoin)
		i = encodeVarintParams(dAtA, i, uint64(len(m.KCoin)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DexDenom) > 0 {
		i -= len(m.DexDenom)
		copy(dAtA[i:], m.DexDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DexDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CollateralDenom) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CollateralDenom) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CollateralDenom) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MaxDeposit.Size()
		i -= size
		if _, err := m.MaxDeposit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.Ltv.Size()
		i -= size
		if _, err := m.Ltv.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.DexDenom) > 0 {
		i -= len(m.DexDenom)
		copy(dAtA[i:], m.DexDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DexDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CAsset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CAsset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CAsset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MinimumLoanSize.Size()
		i -= size
		if _, err := m.MinimumLoanSize.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.BorrowLimit.Size()
		i -= size
		if _, err := m.BorrowLimit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.DexFeeShare.Size()
		i -= size
		if _, err := m.DexFeeShare.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.BaseDexDenom) > 0 {
		i -= len(m.BaseDexDenom)
		copy(dAtA[i:], m.BaseDexDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.BaseDexDenom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DexDenom) > 0 {
		i -= len(m.DexDenom)
		copy(dAtA[i:], m.DexDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DexDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StrategyDenoms) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StrategyDenoms) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StrategyDenoms) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ArbitrageDenoms) > 0 {
		for iNdEx := len(m.ArbitrageDenoms) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ArbitrageDenoms[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	return len(dAtA) - i, nil
}

func (m *FactoryPoolDenom) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FactoryPoolDenom) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FactoryPoolDenom) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MoveThreshold.Size()
		i -= size
		if _, err := m.MoveThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.MinimumPoolSize.Size()
		i -= size
		if _, err := m.MinimumPoolSize.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FactoryPoolDenoms) > 0 {
		for iNdEx := len(m.FactoryPoolDenoms) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FactoryPoolDenoms[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	{
		size, err := m.StrategyDenoms.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.CollateralDenoms) > 0 {
		for iNdEx := len(m.CollateralDenoms) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CollateralDenoms[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.CAssets) > 0 {
		for iNdEx := len(m.CAssets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CAssets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.KCoins) > 0 {
		for iNdEx := len(m.KCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.KCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.DexDenoms) > 0 {
		for iNdEx := len(m.DexDenoms) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DexDenoms[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DexDenom) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.Exponent != 0 {
		n += 1 + sovParams(uint64(m.Exponent))
	}
	l = m.MinTradeLiquidity.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinOrderSize.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.MinDexLiquidity != nil {
		l = m.MinDexLiquidity.Size()
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func (m *KCoin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DexDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if len(m.References) > 0 {
		for _, s := range m.References {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = m.MaxSupply.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxMintAmount.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxBurnAmount.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *ArbitrageDenom) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DexDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.KCoin)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.CAsset)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.BuyThreshold.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.SellThreshold.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.BuyTradeAmount.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.SellTradeAmount.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.RedemptionFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.RedemptionFeeReserveShare.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *CollateralDenom) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DexDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.Ltv.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxDeposit.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *CAsset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DexDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.BaseDexDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.DexFeeShare.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.BorrowLimit.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinimumLoanSize.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *StrategyDenoms) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ArbitrageDenoms) > 0 {
		for _, e := range m.ArbitrageDenoms {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func (m *FactoryPoolDenom) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.MinimumPoolSize.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MoveThreshold.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DexDenoms) > 0 {
		for _, e := range m.DexDenoms {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.KCoins) > 0 {
		for _, e := range m.KCoins {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.CAssets) > 0 {
		for _, e := range m.CAssets {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.CollateralDenoms) > 0 {
		for _, e := range m.CollateralDenoms {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = m.StrategyDenoms.Size()
	n += 1 + l + sovParams(uint64(l))
	if len(m.FactoryPoolDenoms) > 0 {
		for _, e := range m.FactoryPoolDenoms {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DexDenom) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DexDenom: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DexDenom: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exponent", wireType)
			}
			m.Exponent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Exponent |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinTradeLiquidity", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinTradeLiquidity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinOrderSize", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinOrderSize.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDexLiquidity", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.MinDexLiquidity = &v
			if err := m.MinDexLiquidity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KCoin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KCoin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KCoin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DexDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DexDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field References", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.References = append(m.References, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSupply", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMintAmount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxMintAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBurnAmount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxBurnAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ArbitrageDenom) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ArbitrageDenom: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ArbitrageDenom: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DexDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DexDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KCoin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KCoin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CAsset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CAsset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyThreshold", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BuyThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellThreshold", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SellThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyTradeAmount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BuyTradeAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellTradeAmount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SellTradeAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedemptionFee", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RedemptionFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedemptionFeeReserveShare", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RedemptionFeeReserveShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CollateralDenom) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CollateralDenom: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CollateralDenom: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DexDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DexDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ltv", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Ltv.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDeposit", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxDeposit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CAsset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CAsset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CAsset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DexDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DexDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseDexDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseDexDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DexFeeShare", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DexFeeShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowLimit", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BorrowLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumLoanSize", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinimumLoanSize.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StrategyDenoms) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StrategyDenoms: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StrategyDenoms: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArbitrageDenoms", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ArbitrageDenoms = append(m.ArbitrageDenoms, ArbitrageDenom{})
			if err := m.ArbitrageDenoms[len(m.ArbitrageDenoms)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FactoryPoolDenom) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FactoryPoolDenom: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FactoryPoolDenom: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumPoolSize", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinimumPoolSize.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MoveThreshold", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MoveThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DexDenoms", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DexDenoms = append(m.DexDenoms, DexDenom{})
			if err := m.DexDenoms[len(m.DexDenoms)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KCoins = append(m.KCoins, KCoin{})
			if err := m.KCoins[len(m.KCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CAssets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CAssets = append(m.CAssets, CAsset{})
			if err := m.CAssets[len(m.CAssets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralDenoms", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollateralDenoms = append(m.CollateralDenoms, CollateralDenom{})
			if err := m.CollateralDenoms[len(m.CollateralDenoms)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StrategyDenoms", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StrategyDenoms.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FactoryPoolDenoms", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FactoryPoolDenoms = append(m.FactoryPoolDenoms, FactoryPoolDenom{})
			if err := m.FactoryPoolDenoms[len(m.FactoryPoolDenoms)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
