// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kopi/dex/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the dex module's genesis state.
type GenesisState struct {
	Params             Params              `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	LiquidityList      []Liquidity         `protobuf:"bytes,2,rep,name=liquidity_list,json=liquidityList,proto3" json:"liquidity_list"`
	RatioList          []Ratio             `protobuf:"bytes,3,rep,name=ratio_list,json=ratioList,proto3" json:"ratio_list"`
	OrderList          []Order             `protobuf:"bytes,4,rep,name=orderList,proto3" json:"orderList"`
	WalletTradeAmount  []WalletTradeAmount `protobuf:"bytes,5,rep,name=wallet_trade_amount,json=walletTradeAmount,proto3" json:"wallet_trade_amount"`
	LiquidityNextIndex uint64              `protobuf:"varint,6,opt,name=liquidity_next_index,json=liquidityNextIndex,proto3" json:"liquidity_next_index,omitempty"`
	OrderNextIndex     uint64              `protobuf:"varint,7,opt,name=order_next_index,json=orderNextIndex,proto3" json:"order_next_index,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8564f0e5ae5a7c5b, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetLiquidityList() []Liquidity {
	if m != nil {
		return m.LiquidityList
	}
	return nil
}

func (m *GenesisState) GetRatioList() []Ratio {
	if m != nil {
		return m.RatioList
	}
	return nil
}

func (m *GenesisState) GetOrderList() []Order {
	if m != nil {
		return m.OrderList
	}
	return nil
}

func (m *GenesisState) GetWalletTradeAmount() []WalletTradeAmount {
	if m != nil {
		return m.WalletTradeAmount
	}
	return nil
}

func (m *GenesisState) GetLiquidityNextIndex() uint64 {
	if m != nil {
		return m.LiquidityNextIndex
	}
	return 0
}

func (m *GenesisState) GetOrderNextIndex() uint64 {
	if m != nil {
		return m.OrderNextIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "kopi.dex.GenesisState")
}

func init() { proto.RegisterFile("kopi/dex/genesis.proto", fileDescriptor_8564f0e5ae5a7c5b) }

var fileDescriptor_8564f0e5ae5a7c5b = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4f, 0xe2, 0x40,
	0x18, 0xc6, 0xdb, 0x85, 0x65, 0x97, 0x61, 0x97, 0x65, 0x07, 0x34, 0x0d, 0x26, 0x95, 0x70, 0x30,
	0xbd, 0xd8, 0x1a, 0xf0, 0x03, 0x20, 0x17, 0x63, 0x42, 0xfc, 0x83, 0x26, 0x26, 0x5e, 0x9a, 0x62,
	0x27, 0x75, 0x62, 0xdb, 0xa9, 0xed, 0x10, 0xca, 0xb7, 0xf0, 0xec, 0x27, 0xe2, 0xc8, 0xd1, 0x93,
	0x31, 0xf0, 0x45, 0xcc, 0xbc, 0x2d, 0x53, 0x83, 0xde, 0xa6, 0xcf, 0xf3, 0xfb, 0x35, 0xef, 0x3b,
	0x83, 0x76, 0x1f, 0x59, 0x44, 0x2d, 0x97, 0xa4, 0x96, 0x47, 0x42, 0x92, 0xd0, 0xc4, 0x8c, 0x62,
	0xc6, 0x19, 0xfe, 0x2d, 0x72, 0xd3, 0x25, 0x69, 0xbb, 0xe5, 0x31, 0x8f, 0x41, 0x68, 0x89, 0x53,
	0xd6, 0xb7, 0x77, 0xa4, 0x17, 0x39, 0xb1, 0x13, 0xe4, 0x5a, 0x5b, 0x93, 0xb1, 0x4f, 0x9f, 0xa6,
	0xd4, 0xa5, 0x7c, 0x9e, 0x37, 0x2d, 0xd9, 0xc4, 0x0e, 0xa7, 0xec, 0x4b, 0xca, 0x62, 0x97, 0xc4,
	0x79, 0xda, 0x95, 0xe9, 0xcc, 0xf1, 0x7d, 0xc2, 0x6d, 0x1e, 0x3b, 0x2e, 0xb1, 0x9d, 0x80, 0x4d,
	0x43, 0x9e, 0x31, 0xdd, 0x97, 0x12, 0xfa, 0x73, 0x9a, 0x8d, 0x7c, 0xcd, 0x1d, 0x4e, 0xb0, 0x89,
	0x2a, 0xd9, 0x28, 0x9a, 0xda, 0x51, 0x8d, 0x5a, 0xaf, 0x61, 0x6e, 0x56, 0x30, 0x2f, 0x21, 0x1f,
	0x96, 0x17, 0x6f, 0xfb, 0xca, 0x38, 0xa7, 0xf0, 0x00, 0xd5, 0xe5, 0x8c, 0xb6, 0x4f, 0x13, 0xae,
	0xfd, 0xe8, 0x94, 0x8c, 0x5a, 0xaf, 0x59, 0x78, 0xa3, 0x4d, 0x9f, 0xab, 0x7f, 0xa5, 0x30, 0xa2,
	0x09, 0xc7, 0xc7, 0x08, 0xc1, 0x2e, 0x99, 0x5d, 0x02, 0xfb, 0x5f, 0x61, 0x8f, 0x45, 0x97, 0x9b,
	0x55, 0x00, 0xc1, 0xea, 0xa3, 0x2a, 0xec, 0x2a, 0x3e, 0xb4, 0xf2, 0xb6, 0x74, 0x21, 0xaa, 0x8d,
	0x24, 0x39, 0x7c, 0x85, 0x9a, 0xdf, 0x5c, 0x85, 0xf6, 0x13, 0xf4, 0xbd, 0x42, 0xbf, 0x05, 0xe8,
	0x46, 0x30, 0x27, 0x80, 0xe4, 0xbf, 0xfa, 0x3f, 0xdb, 0x2e, 0xf0, 0x11, 0x6a, 0x15, 0xfb, 0x87,
	0x24, 0xe5, 0x36, 0x0d, 0x5d, 0x92, 0x6a, 0x95, 0x8e, 0x6a, 0x94, 0xc7, 0x58, 0x76, 0xe7, 0x24,
	0xe5, 0x67, 0xa2, 0xc1, 0x06, 0x6a, 0xc0, 0x44, 0x9f, 0xe9, 0x5f, 0x40, 0xd7, 0x21, 0x97, 0xe4,
	0x70, 0xb0, 0x58, 0xe9, 0xea, 0x72, 0xa5, 0xab, 0xef, 0x2b, 0x5d, 0x7d, 0x5e, 0xeb, 0xca, 0x72,
	0xad, 0x2b, 0xaf, 0x6b, 0x5d, 0xb9, 0x3b, 0xf0, 0x28, 0x7f, 0x98, 0x4e, 0xcc, 0x7b, 0x16, 0x58,
	0x62, 0xea, 0xc3, 0x80, 0x85, 0x64, 0x0e, 0x47, 0x2b, 0x85, 0x27, 0xe7, 0xf3, 0x88, 0x24, 0x93,
	0x0a, 0xbc, 0x72, 0xff, 0x23, 0x00, 0x00, 0xff, 0xff, 0x86, 0xc8, 0xc3, 0x05, 0xa0, 0x02, 0x00,
	0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OrderNextIndex != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.OrderNextIndex))
		i--
		dAtA[i] = 0x38
	}
	if m.LiquidityNextIndex != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LiquidityNextIndex))
		i--
		dAtA[i] = 0x30
	}
	if len(m.WalletTradeAmount) > 0 {
		for iNdEx := len(m.WalletTradeAmount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WalletTradeAmount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.OrderList) > 0 {
		for iNdEx := len(m.OrderList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OrderList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.RatioList) > 0 {
		for iNdEx := len(m.RatioList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RatioList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.LiquidityList) > 0 {
		for iNdEx := len(m.LiquidityList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LiquidityList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.LiquidityList) > 0 {
		for _, e := range m.LiquidityList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RatioList) > 0 {
		for _, e := range m.RatioList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OrderList) > 0 {
		for _, e := range m.OrderList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.WalletTradeAmount) > 0 {
		for _, e := range m.WalletTradeAmount {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.LiquidityNextIndex != 0 {
		n += 1 + sovGenesis(uint64(m.LiquidityNextIndex))
	}
	if m.OrderNextIndex != 0 {
		n += 1 + sovGenesis(uint64(m.OrderNextIndex))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidityList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidityList = append(m.LiquidityList, Liquidity{})
			if err := m.LiquidityList[len(m.LiquidityList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RatioList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RatioList = append(m.RatioList, Ratio{})
			if err := m.RatioList[len(m.RatioList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderList = append(m.OrderList, Order{})
			if err := m.OrderList[len(m.OrderList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletTradeAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WalletTradeAmount = append(m.WalletTradeAmount, WalletTradeAmount{})
			if err := m.WalletTradeAmount[len(m.WalletTradeAmount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidityNextIndex", wireType)
			}
			m.LiquidityNextIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidityNextIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderNextIndex", wireType)
			}
			m.OrderNextIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrderNextIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
