package types

// DONTCOVER

import (
	sdkerrors "cosmossdk.io/errors"
)

// x/tokenfactory module sentinel errors
var (
	ErrInvalidSigner                  = sdkerrors.Register(ModuleName, 1100, "expected gov account as only signer for proposal message")
	ErrDenomAlreadyExists             = sdkerrors.Register(ModuleName, 1101, "there already is a name with the given denom")
	ErrDenomDoesNotExist              = sdkerrors.Register(ModuleName, 1102, "there is no denom with the given name")
	ErrInvalidAddress                 = sdkerrors.Register(ModuleName, 1103, "invalid address")
	ErrIncorrectAdmin                 = sdkerrors.Register(ModuleName, 1104, "given address is not admin")
	ErrInvalidAmountFormat            = sdkerrors.Register(ModuleName, 1105, "amount format invalid")
	ErrNonPositiveAmount              = sdkerrors.Register(ModuleName, 1106, "amount must be bigger than zero")
	ErrEmptyKCoin                     = sdkerrors.Register(ModuleName, 1107, "given kcoin was empty")
	ErrNoValidPoolDenom               = sdkerrors.Register(ModuleName, 1108, "given denom is no valid factory pool denom")
	ErrPoolAlreadyExists              = sdkerrors.Register(ModuleName, 1109, "liquitidy pool for given pool already exists")
	ErrPoolDoesNotExist               = sdkerrors.Register(ModuleName, 1110, "factory denom has no liquidity pool")
	ErrNegativeLiquidity              = sdkerrors.Register(ModuleName, 1111, "negative liquidity amount")
	ErrSameDenom                      = sdkerrors.Register(ModuleName, 1112, "same denom given twice")
	ErrInsufficientFunds              = sdkerrors.Register(ModuleName, 1113, "insufficient funds")
	ErrInvalidFeeFormat               = sdkerrors.Register(ModuleName, 1114, "invalid fee format")
	ErrPoolFeeTooLarge                = sdkerrors.Register(ModuleName, 1115, "set pool fee too large")
	ErrPoolFeeTooSmall                = sdkerrors.Register(ModuleName, 1116, "set pool fee too small")
	ErrAmountBelowMinimum             = sdkerrors.Register(ModuleName, 1117, "amount below minimum size")
	ErrNotMintable                    = sdkerrors.Register(ModuleName, 1118, "given denom is not mintable")
	ErrAmountTooLarge                 = sdkerrors.Register(ModuleName, 1119, "given amount exceeds user's share of liquidity pool")
	ErrUnlockTooShort                 = sdkerrors.Register(ModuleName, 1120, "unlock period too short")
	ErrLocalTokenDoesNotExist         = sdkerrors.Register(ModuleName, 1121, "local token does not exist")
	ErrCategoryDoesNotExist           = sdkerrors.Register(ModuleName, 1122, "no category for given index")
	ErrOfferNotFound                  = sdkerrors.Register(ModuleName, 1123, "no offer for given index")
	ErrOfferWrongTaker                = sdkerrors.Register(ModuleName, 1124, "incorrect taker for offer")
	ErrInvalidAskDenom                = sdkerrors.Register(ModuleName, 1125, "invalid ask denom")
	ErrVestingNotFound                = sdkerrors.Register(ModuleName, 1126, "no vesting for given index")
	ErrVestingDifferentDenom          = sdkerrors.Register(ModuleName, 1127, "vesting belongs to different token")
	ErrVestingInvalidEnd              = sdkerrors.Register(ModuleName, 1128, "vesting ending must not be before start")
	ErrVestingNegativeSteps           = sdkerrors.Register(ModuleName, 1129, "number of vestings steps must be positive number")
	ErrOfferInvalidVestingEnd         = sdkerrors.Register(ModuleName, 1130, "vesting end must be after offer end")
	ErrVestingTooManySteps            = sdkerrors.Register(ModuleName, 1131, "number of vestings steps too large")
	ErrDescriptionTooLong             = sdkerrors.Register(ModuleName, 1132, "description too long")
	ErrWebsiteURLTooLong              = sdkerrors.Register(ModuleName, 1133, "website url too long")
	ErrWebsiteURLInvalid              = sdkerrors.Register(ModuleName, 1134, "website url invalid")
	ErrChangeTooEarly                 = sdkerrors.Register(ModuleName, 1135, "change too early")
	ErrInvalidMaxPriceFormat          = sdkerrors.Register(ModuleName, 1136, "max price format invalid")
	ErrInvalidLocalToken              = sdkerrors.Register(ModuleName, 1137, "invalid local token")
	ErrInvalidLocalNameSet            = sdkerrors.Register(ModuleName, 1138, "local token name must not be set")
	ErrLocalTokenBurn                 = sdkerrors.Register(ModuleName, 1139, "local token must not be burned")
	ErrDenomAlreadyMoved              = sdkerrors.Register(ModuleName, 1140, "token already has been moved")
	ErrPoolTresholdNotCrossed         = sdkerrors.Register(ModuleName, 1141, "pool value too small")
	ErrPoolTresholdCrossedTooRecently = sdkerrors.Register(ModuleName, 1142, "pool value threshold was crossed too recently")
	ErrInvalidSymbol                  = sdkerrors.Register(ModuleName, 1143, "invalid symbol")
	ErrInvalidName                    = sdkerrors.Register(ModuleName, 1144, "invalid name")
	ErrMintingAlreadyDisabled         = sdkerrors.Register(ModuleName, 1145, "minting already disabled")
	ErrEmptyOfferReceiversList        = sdkerrors.Register(ModuleName, 1146, "empty offer receivers list")
	ErrOfferOpen                      = sdkerrors.Register(ModuleName, 1147, "requested offer is open")
	ErrOfferNotOpen                   = sdkerrors.Register(ModuleName, 1148, "requested offer is not open")
	ErrOfferAmountTooLarge            = sdkerrors.Register(ModuleName, 1149, "given amount is too large")
	ErrTokenConversionAlreadyExists   = sdkerrors.Register(ModuleName, 1150, "token conversion already exists")
	ErrTokenConversionDoesNotExist    = sdkerrors.Register(ModuleName, 1151, "token conversion does not exist")
	ErrTokenConversionListEmpty       = sdkerrors.Register(ModuleName, 1152, "empty token conversions")
	ErrTokenConversionSameToken       = sdkerrors.Register(ModuleName, 1153, "must not convert to same token")
	ErrTokenConversionDuplicateToken  = sdkerrors.Register(ModuleName, 1154, "duplicate conversion token")
	ErrTokenConversionMintable        = sdkerrors.Register(ModuleName, 1155, "conversion token must not be mintable")
)
