// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kopi/tokenfactory/offer.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OfferNextIndex struct {
	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *OfferNextIndex) Reset()         { *m = OfferNextIndex{} }
func (m *OfferNextIndex) String() string { return proto.CompactTextString(m) }
func (*OfferNextIndex) ProtoMessage()    {}
func (*OfferNextIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_558d86d7ad2f036a, []int{0}
}
func (m *OfferNextIndex) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OfferNextIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OfferNextIndex.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OfferNextIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferNextIndex.Merge(m, src)
}
func (m *OfferNextIndex) XXX_Size() int {
	return m.Size()
}
func (m *OfferNextIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferNextIndex.DiscardUnknown(m)
}

var xxx_messageInfo_OfferNextIndex proto.InternalMessageInfo

func (m *OfferNextIndex) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Offer struct {
	Index              uint64                `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	AddressReceiver    string                `protobuf:"bytes,2,opt,name=address_receiver,json=addressReceiver,proto3" json:"address_receiver,omitempty"`
	FactoryDenom       string                `protobuf:"bytes,3,opt,name=factory_denom,json=factoryDenom,proto3" json:"factory_denom,omitempty"`
	AskDenom           string                `protobuf:"bytes,4,opt,name=ask_denom,json=askDenom,proto3" json:"ask_denom,omitempty"`
	FactoryDenomAmount cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=factory_denom_amount,json=factoryDenomAmount,proto3,customtype=cosmossdk.io/math.Int" json:"factory_denom_amount"`
	AskAmount          cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=ask_amount,json=askAmount,proto3,customtype=cosmossdk.io/math.Int" json:"ask_amount"`
	CreatedAt          time.Time             `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at" yaml:"valid_until"`
	ValidUntil         time.Time             `protobuf:"bytes,8,opt,name=valid_until,json=validUntil,proto3,stdtime" json:"valid_until" yaml:"valid_until"`
	VestedUntil        *time.Time            `protobuf:"bytes,9,opt,name=vested_until,json=vestedUntil,proto3,stdtime" json:"vested_until,omitempty" yaml:"vested_until"`
	NumUnlocksSteps    int64                 `protobuf:"varint,10,opt,name=num_unlocks_steps,json=numUnlocksSteps,proto3" json:"num_unlocks_steps,omitempty"`
	Open               bool                  `protobuf:"varint,11,opt,name=open,proto3" json:"open,omitempty"`
}

func (m *Offer) Reset()         { *m = Offer{} }
func (m *Offer) String() string { return proto.CompactTextString(m) }
func (*Offer) ProtoMessage()    {}
func (*Offer) Descriptor() ([]byte, []int) {
	return fileDescriptor_558d86d7ad2f036a, []int{1}
}
func (m *Offer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Offer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Offer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Offer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Offer.Merge(m, src)
}
func (m *Offer) XXX_Size() int {
	return m.Size()
}
func (m *Offer) XXX_DiscardUnknown() {
	xxx_messageInfo_Offer.DiscardUnknown(m)
}

var xxx_messageInfo_Offer proto.InternalMessageInfo

func (m *Offer) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Offer) GetAddressReceiver() string {
	if m != nil {
		return m.AddressReceiver
	}
	return ""
}

func (m *Offer) GetFactoryDenom() string {
	if m != nil {
		return m.FactoryDenom
	}
	return ""
}

func (m *Offer) GetAskDenom() string {
	if m != nil {
		return m.AskDenom
	}
	return ""
}

func (m *Offer) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *Offer) GetValidUntil() time.Time {
	if m != nil {
		return m.ValidUntil
	}
	return time.Time{}
}

func (m *Offer) GetVestedUntil() *time.Time {
	if m != nil {
		return m.VestedUntil
	}
	return nil
}

func (m *Offer) GetNumUnlocksSteps() int64 {
	if m != nil {
		return m.NumUnlocksSteps
	}
	return 0
}

func (m *Offer) GetOpen() bool {
	if m != nil {
		return m.Open
	}
	return false
}

func init() {
	proto.RegisterType((*OfferNextIndex)(nil), "kopi.tokenfactory.OfferNextIndex")
	proto.RegisterType((*Offer)(nil), "kopi.tokenfactory.Offer")
}

func init() { proto.RegisterFile("kopi/tokenfactory/offer.proto", fileDescriptor_558d86d7ad2f036a) }

var fileDescriptor_558d86d7ad2f036a = []byte{
	// 492 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xc1, 0x8a, 0xd3, 0x40,
	0x18, 0xc7, 0x3b, 0x6e, 0xbb, 0xb6, 0xd3, 0xea, 0xba, 0x63, 0x85, 0x50, 0xd9, 0x24, 0x54, 0x90,
	0x28, 0x98, 0x80, 0xde, 0xc4, 0xcb, 0x16, 0x2f, 0xbd, 0xb8, 0x10, 0xdd, 0x83, 0x0a, 0x86, 0x69,
	0x32, 0xed, 0x86, 0x64, 0x66, 0x42, 0x66, 0x52, 0xda, 0xb7, 0xd8, 0xc7, 0xea, 0x71, 0x8f, 0xe2,
	0x21, 0x4a, 0xfb, 0x04, 0xee, 0x13, 0xc8, 0xcc, 0x64, 0xa1, 0x0b, 0x82, 0xc2, 0xde, 0xbe, 0xfc,
	0xbe, 0xff, 0xf7, 0x9b, 0x09, 0x1f, 0x03, 0x4f, 0x32, 0x5e, 0xa4, 0x81, 0xe4, 0x19, 0x61, 0x73,
	0x1c, 0x4b, 0x5e, 0xae, 0x03, 0x3e, 0x9f, 0x93, 0xd2, 0x2f, 0x4a, 0x2e, 0x39, 0x3a, 0x56, 0x6d,
	0x7f, 0xbf, 0x3d, 0x72, 0x16, 0x9c, 0x2f, 0x72, 0x12, 0xe8, 0xc0, 0xac, 0x9a, 0x07, 0x32, 0xa5,
	0x44, 0x48, 0x4c, 0x0b, 0x33, 0x33, 0x1a, 0x2e, 0xf8, 0x82, 0xeb, 0x32, 0x50, 0x95, 0xa1, 0xe3,
	0xe7, 0xf0, 0xe1, 0x99, 0x12, 0x7f, 0x20, 0x2b, 0x39, 0x65, 0x09, 0x59, 0xa1, 0x21, 0xec, 0xa4,
	0xaa, 0xb0, 0x80, 0x0b, 0xbc, 0x76, 0x68, 0x3e, 0xc6, 0xbf, 0xdb, 0xb0, 0xa3, 0x83, 0x7f, 0xef,
	0xa3, 0x17, 0xf0, 0x11, 0x4e, 0x92, 0x92, 0x08, 0x11, 0x95, 0x24, 0x26, 0xe9, 0x92, 0x94, 0xd6,
	0x3d, 0x17, 0x78, 0xbd, 0xf0, 0xa8, 0xe1, 0x61, 0x83, 0xd1, 0x33, 0xf8, 0xa0, 0xb9, 0x74, 0x94,
	0x10, 0xc6, 0xa9, 0x75, 0xa0, 0x73, 0x83, 0x06, 0xbe, 0x57, 0x0c, 0x3d, 0x85, 0x3d, 0x2c, 0xb2,
	0x26, 0xd0, 0xd6, 0x81, 0x2e, 0x16, 0x99, 0x69, 0x9e, 0xc1, 0xe1, 0x2d, 0x43, 0x84, 0x29, 0xaf,
	0x98, 0xb4, 0x3a, 0x2e, 0xf0, 0x06, 0x93, 0x93, 0x4d, 0xed, 0xb4, 0x7e, 0xd4, 0xce, 0x93, 0x98,
	0x0b, 0xca, 0x85, 0x48, 0x32, 0x3f, 0xe5, 0x01, 0xc5, 0xf2, 0xc2, 0x9f, 0x32, 0x19, 0xa2, 0xfd,
	0x73, 0x4e, 0xf5, 0x20, 0x7a, 0x07, 0xa1, 0x3a, 0xad, 0xd1, 0x1c, 0xfe, 0x8f, 0x46, 0x5d, 0xaf,
	0x99, 0xfe, 0x0c, 0x61, 0x5c, 0x12, 0x2c, 0x49, 0x12, 0x61, 0x69, 0xdd, 0x77, 0x81, 0xd7, 0x7f,
	0x3d, 0xf2, 0xcd, 0x3e, 0xfc, 0x9b, 0x7d, 0xf8, 0x9f, 0x6e, 0xf6, 0x31, 0xb1, 0x95, 0xf9, 0xba,
	0x76, 0xd0, 0x1a, 0xd3, 0xfc, 0xed, 0x78, 0x89, 0xf3, 0x34, 0x89, 0x2a, 0x26, 0xd3, 0x7c, 0x7c,
	0xf9, 0xd3, 0x01, 0x61, 0xaf, 0xb1, 0x9d, 0x4a, 0xf4, 0x15, 0xf6, 0xf7, 0xda, 0x56, 0xf7, 0xce,
	0x6e, 0xa8, 0xc9, 0xb9, 0x02, 0xe8, 0x1b, 0x1c, 0x2c, 0x89, 0x50, 0xd7, 0x36, 0xf6, 0xde, 0x3f,
	0xed, 0xce, 0xa6, 0x76, 0xc0, 0x75, 0xed, 0x3c, 0x6e, 0xec, 0x7b, 0xd3, 0x46, 0xdf, 0x37, 0xc8,
	0xf8, 0x5f, 0xc2, 0x63, 0x56, 0xd1, 0xa8, 0x62, 0x39, 0x8f, 0x33, 0x11, 0x09, 0x49, 0x0a, 0x61,
	0x41, 0x17, 0x78, 0x07, 0xe1, 0x11, 0xab, 0xe8, 0xb9, 0xe1, 0x1f, 0x15, 0x46, 0x08, 0xb6, 0x79,
	0x41, 0x98, 0xd5, 0x77, 0x81, 0xd7, 0x0d, 0x75, 0x3d, 0x99, 0x6e, 0xb6, 0x36, 0xb8, 0xda, 0xda,
	0xe0, 0xd7, 0xd6, 0x06, 0x97, 0x3b, 0xbb, 0x75, 0xb5, 0xb3, 0x5b, 0xdf, 0x77, 0x76, 0xeb, 0x4b,
	0xb0, 0x48, 0xe5, 0x45, 0x35, 0xf3, 0x63, 0x4e, 0x03, 0xf5, 0x14, 0x5e, 0x51, 0xce, 0xc8, 0x5a,
	0x97, 0xc1, 0xea, 0xf6, 0xb3, 0x91, 0xeb, 0x82, 0x88, 0xd9, 0xa1, 0xfe, 0x99, 0x37, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xaa, 0xa1, 0x02, 0xc4, 0x58, 0x03, 0x00, 0x00,
}

func (m *OfferNextIndex) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OfferNextIndex) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OfferNextIndex) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Index != 0 {
		i = encodeVarintOffer(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Offer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Offer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Offer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Open {
		i--
		if m.Open {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.NumUnlocksSteps != 0 {
		i = encodeVarintOffer(dAtA, i, uint64(m.NumUnlocksSteps))
		i--
		dAtA[i] = 0x50
	}
	if m.VestedUntil != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.VestedUntil, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.VestedUntil):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintOffer(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x4a
	}
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ValidUntil, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ValidUntil):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintOffer(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x42
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CreatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintOffer(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x3a
	{
		size := m.AskAmount.Size()
		i -= size
		if _, err := m.AskAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintOffer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.FactoryDenomAmount.Size()
		i -= size
		if _, err := m.FactoryDenomAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintOffer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.AskDenom) > 0 {
		i -= len(m.AskDenom)
		copy(dAtA[i:], m.AskDenom)
		i = encodeVarintOffer(dAtA, i, uint64(len(m.AskDenom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.FactoryDenom) > 0 {
		i -= len(m.FactoryDenom)
		copy(dAtA[i:], m.FactoryDenom)
		i = encodeVarintOffer(dAtA, i, uint64(len(m.FactoryDenom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AddressReceiver) > 0 {
		i -= len(m.AddressReceiver)
		copy(dAtA[i:], m.AddressReceiver)
		i = encodeVarintOffer(dAtA, i, uint64(len(m.AddressReceiver)))
		i--
		dAtA[i] = 0x12
	}
	if m.Index != 0 {
		i = encodeVarintOffer(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintOffer(dAtA []byte, offset int, v uint64) int {
	offset -= sovOffer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OfferNextIndex) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovOffer(uint64(m.Index))
	}
	return n
}

func (m *Offer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovOffer(uint64(m.Index))
	}
	l = len(m.AddressReceiver)
	if l > 0 {
		n += 1 + l + sovOffer(uint64(l))
	}
	l = len(m.FactoryDenom)
	if l > 0 {
		n += 1 + l + sovOffer(uint64(l))
	}
	l = len(m.AskDenom)
	if l > 0 {
		n += 1 + l + sovOffer(uint64(l))
	}
	l = m.FactoryDenomAmount.Size()
	n += 1 + l + sovOffer(uint64(l))
	l = m.AskAmount.Size()
	n += 1 + l + sovOffer(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovOffer(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ValidUntil)
	n += 1 + l + sovOffer(uint64(l))
	if m.VestedUntil != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.VestedUntil)
		n += 1 + l + sovOffer(uint64(l))
	}
	if m.NumUnlocksSteps != 0 {
		n += 1 + sovOffer(uint64(m.NumUnlocksSteps))
	}
	if m.Open {
		n += 2
	}
	return n
}

func sovOffer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOffer(x uint64) (n int) {
	return sovOffer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OfferNextIndex) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOffer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OfferNextIndex: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OfferNextIndex: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOffer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOffer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Offer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOffer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Offer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Offer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressReceiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOffer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOffer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddressReceiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FactoryDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOffer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOffer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FactoryDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AskDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOffer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOffer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AskDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FactoryDenomAmount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOffer
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOffer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FactoryDenomAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AskAmount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOffer
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOffer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AskAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOffer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOffer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidUntil", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOffer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOffer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ValidUntil, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestedUntil", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOffer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOffer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VestedUntil == nil {
				m.VestedUntil = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.VestedUntil, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumUnlocksSteps", wireType)
			}
			m.NumUnlocksSteps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumUnlocksSteps |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Open", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Open = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipOffer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOffer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOffer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOffer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOffer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOffer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOffer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOffer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOffer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOffer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOffer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOffer = fmt.Errorf("proto: unexpected end of group")
)
