// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kopi/tokenfactory/vesting.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type VestingNextIndex struct {
	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *VestingNextIndex) Reset()         { *m = VestingNextIndex{} }
func (m *VestingNextIndex) String() string { return proto.CompactTextString(m) }
func (*VestingNextIndex) ProtoMessage()    {}
func (*VestingNextIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1d09f17a36f6108, []int{0}
}
func (m *VestingNextIndex) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VestingNextIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VestingNextIndex.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VestingNextIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VestingNextIndex.Merge(m, src)
}
func (m *VestingNextIndex) XXX_Size() int {
	return m.Size()
}
func (m *VestingNextIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_VestingNextIndex.DiscardUnknown(m)
}

var xxx_messageInfo_VestingNextIndex proto.InternalMessageInfo

func (m *VestingNextIndex) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Vesting struct {
	Index                 uint64                      `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Address               string                      `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	FactoryDenom          string                      `protobuf:"bytes,3,opt,name=factory_denom,json=factoryDenom,proto3" json:"factory_denom,omitempty"`
	AmountVested          cosmossdk_io_math.Int       `protobuf:"bytes,4,opt,name=amount_vested,json=amountVested,proto3,customtype=cosmossdk.io/math.Int" json:"amount_vested"`
	AmountUnlockedPerStep cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=amount_unlocked_per_step,json=amountUnlockedPerStep,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"amount_unlocked_per_step"`
	AmountLeft            cosmossdk_io_math.Int       `protobuf:"bytes,6,opt,name=amount_left,json=amountLeft,proto3,customtype=cosmossdk.io/math.Int" json:"amount_left"`
	NextUnlocks           []time.Time                 `protobuf:"bytes,7,rep,name=next_unlocks,json=nextUnlocks,proto3,stdtime" json:"next_unlocks" yaml:"next_unlocks"`
}

func (m *Vesting) Reset()         { *m = Vesting{} }
func (m *Vesting) String() string { return proto.CompactTextString(m) }
func (*Vesting) ProtoMessage()    {}
func (*Vesting) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1d09f17a36f6108, []int{1}
}
func (m *Vesting) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Vesting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Vesting.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Vesting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vesting.Merge(m, src)
}
func (m *Vesting) XXX_Size() int {
	return m.Size()
}
func (m *Vesting) XXX_DiscardUnknown() {
	xxx_messageInfo_Vesting.DiscardUnknown(m)
}

var xxx_messageInfo_Vesting proto.InternalMessageInfo

func (m *Vesting) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Vesting) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Vesting) GetFactoryDenom() string {
	if m != nil {
		return m.FactoryDenom
	}
	return ""
}

func (m *Vesting) GetNextUnlocks() []time.Time {
	if m != nil {
		return m.NextUnlocks
	}
	return nil
}

func init() {
	proto.RegisterType((*VestingNextIndex)(nil), "kopi.tokenfactory.VestingNextIndex")
	proto.RegisterType((*Vesting)(nil), "kopi.tokenfactory.Vesting")
}

func init() { proto.RegisterFile("kopi/tokenfactory/vesting.proto", fileDescriptor_f1d09f17a36f6108) }

var fileDescriptor_f1d09f17a36f6108 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x8a, 0xd3, 0x50,
	0x14, 0x86, 0x1b, 0x3b, 0x33, 0xc5, 0xdb, 0x0e, 0x68, 0x9c, 0x81, 0x4b, 0xc5, 0xa4, 0x74, 0x36,
	0xd9, 0x98, 0x0b, 0xba, 0x73, 0xe1, 0xa2, 0xcc, 0xa6, 0x30, 0x88, 0x44, 0x9d, 0x85, 0x88, 0x25,
	0x4d, 0x4e, 0x33, 0xa1, 0xbd, 0xf7, 0x84, 0xdc, 0x53, 0x69, 0xde, 0x62, 0x1e, 0xc1, 0xc7, 0x99,
	0xe5, 0x2c, 0xc5, 0x45, 0x95, 0xf6, 0x0d, 0x7c, 0x02, 0xb9, 0xb9, 0x09, 0x54, 0x74, 0xe1, 0xee,
	0xdc, 0x3f, 0xff, 0xff, 0xf1, 0x87, 0x73, 0x98, 0xbf, 0xc4, 0x22, 0x17, 0x84, 0x4b, 0x50, 0x8b,
	0x38, 0x21, 0x2c, 0x2b, 0xf1, 0x05, 0x34, 0xe5, 0x2a, 0x0b, 0x8b, 0x12, 0x09, 0xdd, 0xc7, 0xc6,
	0x10, 0x1e, 0x1a, 0x86, 0x7e, 0x86, 0x98, 0xad, 0x40, 0xd4, 0x86, 0xf9, 0x7a, 0x21, 0x28, 0x97,
	0xa0, 0x29, 0x96, 0x85, 0xcd, 0x0c, 0xcf, 0x32, 0xcc, 0xb0, 0x1e, 0x85, 0x99, 0xac, 0x3a, 0x0e,
	0xd8, 0xa3, 0x6b, 0x8b, 0x7e, 0x03, 0x1b, 0x9a, 0xaa, 0x14, 0x36, 0xee, 0x19, 0x3b, 0xce, 0xcd,
	0xc0, 0x9d, 0x91, 0x13, 0x1c, 0x45, 0xf6, 0x31, 0xfe, 0xda, 0x65, 0xbd, 0xc6, 0xfa, 0x6f, 0x87,
	0xcb, 0x59, 0x2f, 0x4e, 0xd3, 0x12, 0xb4, 0xe6, 0x0f, 0x46, 0x4e, 0xf0, 0x30, 0x6a, 0x9f, 0xee,
	0x05, 0x3b, 0x6d, 0x7a, 0xce, 0x52, 0x50, 0x28, 0x79, 0xb7, 0xfe, 0x3e, 0x68, 0xc4, 0x4b, 0xa3,
	0xb9, 0x13, 0x76, 0x1a, 0x4b, 0x5c, 0x2b, 0x9a, 0x99, 0x9f, 0x85, 0x94, 0x1f, 0x8d, 0x9c, 0x60,
	0x30, 0x79, 0x76, 0xb7, 0xf5, 0x3b, 0xdf, 0xb7, 0xfe, 0x79, 0x82, 0x5a, 0xa2, 0xd6, 0xe9, 0x32,
	0xcc, 0x51, 0xc8, 0x98, 0x6e, 0xc2, 0xa9, 0xa2, 0x68, 0x60, 0x33, 0xd7, 0x75, 0xc4, 0xfd, 0xc4,
	0x78, 0xc3, 0x58, 0xab, 0x15, 0x26, 0x4b, 0x48, 0x67, 0x05, 0x94, 0x33, 0x4d, 0x50, 0xf0, 0xe3,
	0x1a, 0x77, 0xd1, 0xe0, 0x9e, 0xfe, 0x8d, 0xbb, 0x82, 0x2c, 0x4e, 0xaa, 0x4b, 0x48, 0xa2, 0x73,
	0x0b, 0xf9, 0xd0, 0x30, 0xde, 0x42, 0xf9, 0x8e, 0xa0, 0x70, 0x5f, 0xb3, 0x7e, 0x43, 0x5f, 0xc1,
	0x82, 0xf8, 0xc9, 0xff, 0xf4, 0x63, 0x36, 0x71, 0x05, 0x0b, 0x72, 0x3f, 0xb3, 0x81, 0x82, 0x4d,
	0xdb, 0x4d, 0xf3, 0xde, 0xa8, 0x1b, 0xf4, 0x5f, 0x0c, 0x43, 0xbb, 0xba, 0xb0, 0x5d, 0x5d, 0xf8,
	0xbe, 0x5d, 0xdd, 0xc4, 0x37, 0xf0, 0x5f, 0x5b, 0xff, 0x49, 0x15, 0xcb, 0xd5, 0xab, 0xf1, 0x61,
	0x7a, 0x7c, 0xfb, 0xc3, 0x77, 0xa2, 0xbe, 0x91, 0x6c, 0x4f, 0x3d, 0x99, 0xde, 0xed, 0x3c, 0xe7,
	0x7e, 0xe7, 0x39, 0x3f, 0x77, 0x9e, 0x73, 0xbb, 0xf7, 0x3a, 0xf7, 0x7b, 0xaf, 0xf3, 0x6d, 0xef,
	0x75, 0x3e, 0x8a, 0x2c, 0xa7, 0x9b, 0xf5, 0x3c, 0x4c, 0x50, 0x0a, 0x73, 0x3b, 0xcf, 0x25, 0x2a,
	0xa8, 0xea, 0x51, 0x6c, 0xfe, 0xbc, 0x34, 0xaa, 0x0a, 0xd0, 0xf3, 0x93, 0xba, 0xcc, 0xcb, 0xdf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x58, 0x48, 0xd7, 0x6b, 0x8b, 0x02, 0x00, 0x00,
}

func (m *VestingNextIndex) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VestingNextIndex) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VestingNextIndex) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Index != 0 {
		i = encodeVarintVesting(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Vesting) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Vesting) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Vesting) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NextUnlocks) > 0 {
		for iNdEx := len(m.NextUnlocks) - 1; iNdEx >= 0; iNdEx-- {
			n, err := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.NextUnlocks[iNdEx], dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.NextUnlocks[iNdEx]):])
			if err != nil {
				return 0, err
			}
			i -= n
			i = encodeVarintVesting(dAtA, i, uint64(n))
			i--
			dAtA[i] = 0x3a
		}
	}
	{
		size := m.AmountLeft.Size()
		i -= size
		if _, err := m.AmountLeft.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVesting(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.AmountUnlockedPerStep.Size()
		i -= size
		if _, err := m.AmountUnlockedPerStep.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVesting(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.AmountVested.Size()
		i -= size
		if _, err := m.AmountVested.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVesting(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.FactoryDenom) > 0 {
		i -= len(m.FactoryDenom)
		copy(dAtA[i:], m.FactoryDenom)
		i = encodeVarintVesting(dAtA, i, uint64(len(m.FactoryDenom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintVesting(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.Index != 0 {
		i = encodeVarintVesting(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintVesting(dAtA []byte, offset int, v uint64) int {
	offset -= sovVesting(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VestingNextIndex) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovVesting(uint64(m.Index))
	}
	return n
}

func (m *Vesting) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovVesting(uint64(m.Index))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovVesting(uint64(l))
	}
	l = len(m.FactoryDenom)
	if l > 0 {
		n += 1 + l + sovVesting(uint64(l))
	}
	l = m.AmountVested.Size()
	n += 1 + l + sovVesting(uint64(l))
	l = m.AmountUnlockedPerStep.Size()
	n += 1 + l + sovVesting(uint64(l))
	l = m.AmountLeft.Size()
	n += 1 + l + sovVesting(uint64(l))
	if len(m.NextUnlocks) > 0 {
		for _, e := range m.NextUnlocks {
			l = github_com_cosmos_gogoproto_types.SizeOfStdTime(e)
			n += 1 + l + sovVesting(uint64(l))
		}
	}
	return n
}

func sovVesting(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVesting(x uint64) (n int) {
	return sovVesting(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VestingNextIndex) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVesting
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VestingNextIndex: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VestingNextIndex: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVesting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVesting(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVesting
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Vesting) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVesting
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Vesting: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Vesting: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVesting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVesting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVesting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVesting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FactoryDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVesting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVesting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVesting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FactoryDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountVested", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVesting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVesting
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVesting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountVested.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountUnlockedPerStep", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVesting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVesting
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVesting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountUnlockedPerStep.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountLeft", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVesting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVesting
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVesting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountLeft.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextUnlocks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVesting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVesting
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVesting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NextUnlocks = append(m.NextUnlocks, time.Time{})
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&(m.NextUnlocks[len(m.NextUnlocks)-1]), dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVesting(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVesting
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVesting(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVesting
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVesting
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVesting
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVesting
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVesting
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVesting
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVesting        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVesting          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVesting = fmt.Errorf("proto: unexpected end of group")
)
