syntax = "proto3";
package kopi.reserve;

import "amino/amino.proto";
import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "kopi/reserve/params.proto";

option go_package = "github.com/kopi-money/kopi/x/reserve/types";

// Msg defines the Msg service.
service Msg {
  option (cosmos.msg.v1.service) = true;

  rpc UpdateKCoinBurnShare  (MsgUpdateKCoinBurnShare)  returns (Void);
  rpc UpdateBuyThreshold    (MsgUpdateBuyThreshold)    returns (Void);
  rpc UpdateSellThreshold   (MsgUpdateSellThreshold)   returns (Void);
  rpc UpdateTradeFeeStakers (MsgUpdateTradeFeeStakers) returns (Void);

  rpc Burn(MsgBurn) returns (Void);
}

message MsgUpdateTradeFeeStakers {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/reserve/MsgUpdateTradeFeeStakers";
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  string trade_fee_base_income_share_to_stakers = 2;
  string trade_fee_other_income_share_to_stakers = 3;
}

message MsgBurn {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string denom = 2;
  string amount = 3;
}

message MsgUpdateBuyThreshold {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/reserve/MsgUpdateBuyThreshold";
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  string buy_threshold = 2;
}

message MsgUpdateSellThreshold {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/reserve/MsgUpdateSellThreshold";
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  string sell_threshold = 2;
}

message MsgUpdateKCoinBurnShare {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "kopi/x/reserve/MsgUpdateKCoinBurnShare";
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  string kcoin_burn_share = 2;
}

message Void {}