// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kopi/ls/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisUndelegation struct {
	Index   uint64                `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Address string                `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Amount  cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
}

func (m *GenesisUndelegation) Reset()         { *m = GenesisUndelegation{} }
func (m *GenesisUndelegation) String() string { return proto.CompactTextString(m) }
func (*GenesisUndelegation) ProtoMessage()    {}
func (*GenesisUndelegation) Descriptor() ([]byte, []int) {
	return fileDescriptor_27cfe68672f816e6, []int{0}
}
func (m *GenesisUndelegation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisUndelegation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisUndelegation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisUndelegation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisUndelegation.Merge(m, src)
}
func (m *GenesisUndelegation) XXX_Size() int {
	return m.Size()
}
func (m *GenesisUndelegation) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisUndelegation.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisUndelegation proto.InternalMessageInfo

func (m *GenesisUndelegation) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *GenesisUndelegation) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// GenesisState defines the ls module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params                 Params                 `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Undelegations          []*GenesisUndelegation `protobuf:"bytes,2,rep,name=undelegations,proto3" json:"undelegations,omitempty"`
	UndelegationsNextIndex uint64                 `protobuf:"varint,3,opt,name=undelegations_next_index,json=undelegationsNextIndex,proto3" json:"undelegations_next_index,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_27cfe68672f816e6, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetUndelegations() []*GenesisUndelegation {
	if m != nil {
		return m.Undelegations
	}
	return nil
}

func (m *GenesisState) GetUndelegationsNextIndex() uint64 {
	if m != nil {
		return m.UndelegationsNextIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisUndelegation)(nil), "kopi.ls.GenesisUndelegation")
	proto.RegisterType((*GenesisState)(nil), "kopi.ls.GenesisState")
}

func init() { proto.RegisterFile("kopi/ls/genesis.proto", fileDescriptor_27cfe68672f816e6) }

var fileDescriptor_27cfe68672f816e6 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x41, 0x4b, 0x02, 0x41,
	0x14, 0xde, 0xc9, 0x52, 0x1c, 0x8d, 0x68, 0xd3, 0x58, 0xa4, 0x56, 0x11, 0x82, 0x25, 0x68, 0x07,
	0x8c, 0xa0, 0x5b, 0xb0, 0x97, 0xf0, 0x12, 0xb1, 0xd1, 0xa5, 0x8b, 0x8c, 0xee, 0xb0, 0x0e, 0x3a,
	0x33, 0x8b, 0x33, 0xc2, 0x0a, 0xfd, 0x88, 0x7e, 0x46, 0xc7, 0x7e, 0x42, 0x47, 0x8f, 0x1e, 0xa3,
	0x83, 0x84, 0x1e, 0xfa, 0x1b, 0x31, 0xb3, 0x6b, 0x24, 0x74, 0x19, 0xde, 0x7c, 0xdf, 0x7b, 0xdf,
	0xfb, 0xde, 0x7b, 0xb0, 0x3e, 0x12, 0x09, 0x45, 0x63, 0x89, 0x62, 0xc2, 0x89, 0xa4, 0xd2, 0x4f,
	0x26, 0x42, 0x09, 0xbb, 0xa4, 0x61, 0x7f, 0x2c, 0x1b, 0x87, 0x98, 0x51, 0x2e, 0x90, 0x79, 0x33,
	0xae, 0x51, 0x8b, 0x45, 0x2c, 0x4c, 0x88, 0x74, 0xb4, 0x41, 0x37, 0x42, 0x09, 0x9e, 0x60, 0x96,
	0xeb, 0xb4, 0x9f, 0xe1, 0xd1, 0x6d, 0x26, 0xfc, 0xc8, 0x23, 0x32, 0x26, 0x31, 0x56, 0x54, 0x70,
	0xbb, 0x06, 0xf7, 0x28, 0x8f, 0x48, 0xea, 0x80, 0x16, 0xf0, 0x76, 0xc3, 0xec, 0x63, 0x3b, 0xb0,
	0x84, 0xa3, 0x68, 0x42, 0xa4, 0x74, 0x76, 0x5a, 0xc0, 0x2b, 0x87, 0x9b, 0xaf, 0x7d, 0x05, 0x8b,
	0x98, 0x89, 0x29, 0x57, 0x4e, 0xa1, 0x05, 0xbc, 0x6a, 0x70, 0x3a, 0x5f, 0x36, 0xad, 0xcf, 0x65,
	0xb3, 0x3e, 0x10, 0x92, 0x09, 0x29, 0xa3, 0x91, 0x4f, 0x05, 0x62, 0x58, 0x0d, 0xfd, 0x2e, 0x57,
	0x61, 0x9e, 0xdc, 0x7e, 0x07, 0xb0, 0x9a, 0xb7, 0x7f, 0x50, 0x58, 0x11, 0xbb, 0x03, 0x8b, 0x99,
	0x3d, 0xd3, 0xb8, 0xd2, 0x39, 0xf0, 0xf3, 0x39, 0xfd, 0x7b, 0x03, 0x07, 0x65, 0x2d, 0xfc, 0xfa,
	0xfd, 0x76, 0x0e, 0xc2, 0x3c, 0xd3, 0x0e, 0xe0, 0xfe, 0xf4, 0x8f, 0x77, 0xed, 0xad, 0xe0, 0x55,
	0x3a, 0x27, 0xbf, 0xa5, 0xff, 0x0c, 0x18, 0x6e, 0x97, 0xd8, 0xd7, 0xd0, 0xd9, 0x02, 0x7a, 0x9c,
	0xa4, 0xaa, 0x97, 0xad, 0xa0, 0x60, 0x56, 0x70, 0xbc, 0xc5, 0xdf, 0x91, 0x54, 0x75, 0x35, 0x1b,
	0xdc, 0xcc, 0x57, 0x2e, 0x58, 0xac, 0x5c, 0xf0, 0xb5, 0x72, 0xc1, 0xcb, 0xda, 0xb5, 0x16, 0x6b,
	0xd7, 0xfa, 0x58, 0xbb, 0xd6, 0xd3, 0x59, 0x4c, 0xd5, 0x70, 0xda, 0xf7, 0x07, 0x82, 0x21, 0x6d,
	0xe5, 0x82, 0x09, 0x4e, 0x66, 0x26, 0x44, 0xa9, 0x3e, 0x84, 0x9a, 0x25, 0x44, 0xf6, 0x8b, 0xe6,
	0x10, 0x97, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x54, 0x82, 0x87, 0xb9, 0xe9, 0x01, 0x00, 0x00,
}

func (m *GenesisUndelegation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisUndelegation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisUndelegation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.Index != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UndelegationsNextIndex != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.UndelegationsNextIndex))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Undelegations) > 0 {
		for iNdEx := len(m.Undelegations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Undelegations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisUndelegation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovGenesis(uint64(m.Index))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Undelegations) > 0 {
		for _, e := range m.Undelegations {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.UndelegationsNextIndex != 0 {
		n += 1 + sovGenesis(uint64(m.UndelegationsNextIndex))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisUndelegation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisUndelegation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisUndelegation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Undelegations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Undelegations = append(m.Undelegations, &GenesisUndelegation{})
			if err := m.Undelegations[len(m.Undelegations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UndelegationsNextIndex", wireType)
			}
			m.UndelegationsNextIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UndelegationsNextIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
